### ISSUE TITLE
Check if AR is available function

### ISSUE THREAD

**Issue by cjrorvik** [viromedia/viro#108]
Are there any utils functions for the React Native lib that can check whether the user's phone has AR available or not? I can use react-native-device-info and check the device model up against the supported devices, but I find it a bit weird to do it that way.

**Comment by manbod** [comment]
Hi Carl,

Thanks for reaching out to us. 

If your requirement is to only run your app on ar enabled devices, for iOS you could achieve it by following steps mentioned here https://stackoverflow.com/questions/46569624/xcode-how-do-i-set-compatible-devices-to-only-arkit-compatible-devices

Otherwise, if the use case is to enable AR specific features in a scene in your app only on AR enabled devices, then you'll have to add a custom RN module to check for this. You can write a custom RN module for iOS that checks the isSupported flag in the ARConfiguration class: 

https://stackoverflow.com/questions/46642418/arkit-how-to-correctly-check-for-supported-devices

For Android, you'll have to check the device models to ensure the hardware supports ARCore. 

We plan to add support for this in a future release. 

Let me know if you know if you have more questions. Thanks!

**Comment by domvon** [comment]
Thanks manbod. We will also need a way to disable AR features on phones that don't support it (iOS and Android). So we'd definitely use it if it's added to Viro.

**Comment by cjrorvik** [comment]
Looking for a way to integrate AR as an extra feature into an app for all devices. Then hiding the way into the AR-features or a pop-up saying something like "only these phones supports this Ar feature" But the app has to compile and work for phones that do not support AR as well :)

**Comment by dam00n** [comment]
@cjrorvik in ViroReact 2.4, we added a new util IsARSupportOnDevice -> https://docs.viromedia.com/docs/isarsupportedondevice

This should solve for your use case across ARCore and ARKit.

Release notes and upgrade instructions for ViroReact 2.4 here -> https://docs.viromedia.com/docs/releases

**Comment by cjrorvik** [comment]
Nice! Thanks 🥇

**Comment by realchiu** [comment]
IsARSupportOnDevice will trigger support callback even when iphone6/5s is being used. I have tried to check again 5seconds after first check(reference from #428 ), but still give support callback. It seems ARKit is not supported in iphone6/iphone5s due the the chip version. Is this a bug?

**Comment by ambojialur** [comment]
Here is the solution - https://github.com/viromedia/viro/issues/492#issuecomment-453934878

    // Get array containing installed apps
    var installedApps = require("react-native-installed-packages");
    let appArray = installedApps.getApps();

    // Check app_array for ar core package
    var arPackage = appArray.find(function (_package) {
      return _package == "com.google.ar.core";
    });

    if (typeof arPackage === "undefined") {
      console.log("AR not support");
    } else {
      console.log("AR support");
    }
