### ISSUE TITLE
arcore-for-all integration

### ISSUE THREAD

**Issue by hmontes** [viromedia/viro#113]
Hi

It's possible to integrate https://github.com/tomthecarrot/arcore-for-all to the react-native projects?

With this. you can target more android phones.

Thanks

**Comment by hmontes** [comment]
I preliminary test this

your-project/node_modules/react-viro/android/arcore_client/arcore_client.aar with the .arr file in the arcore-for-all package and works. Maybe you can integrate a better solution for that.

**Comment by achuvm** [comment]
Hi @hmontes,

Glad you found that solution which is the way we recommend you integrate with that updated library.

However, we don't plan on offering an easier way to support that library because it's not an official release of ARCore and hopefully when ARCore comes out of Beta it will support many more devices, rendering the need for the ARCore-for-all modification unnecessary. In the meantime, the existing solution you discovered accomplishes the same task.

For posterity's sake, the way to use that library is to:

1. create a React Viro project
2. follow instructions here to set up Android Studio: https://docs.viromedia.com/docs/installing-viro-android
3. replace `<your-project>/node_modules/react-viro/android/arcore_client/arcore_client.aar` with the `.aar` file from that repo
4. open Android Studio and build your application using the modified .aar file

Thanks for reaching out!

- Andy

**Comment by dam00n** [comment]
Closing this issue as a solution provided.
