### ISSUE TITLE
Video withou audio in it!

### ISSUE THREAD

**Issue by aminesig** [viromedia/viro#128]
The audio is missing from the viro360video remote link !

**Comment by achuvm** [comment]
Hi @aminesig,

We tested this on our end and it seems to work.

In order to help you debug this, can you provide the following information:

What device(s) are you seeing this on?
Can you provide a link to the video you're trying to test?
Can we get a snippet of code containing the `Viro360Video` component? is the `muted` prop set to  `true` or the `volume` prop set to 0?

Thanks,

**Comment by aminesig** [comment]
You are right ! the volume was muted in a missed state value, what a dumb issue opening ! sorry for that

**Comment by achuvm** [comment]
Hi @aminesig,

No problem! Glad it was something simple and not an issue with the platform!
