### ISSUE TITLE
Shadow on white ViroText

### ISSUE THREAD

**Issue by cjrorvik** [viromedia/viro#130]
I am rendering white ViroText in the AR space inside a ViroFlexView, and I was wondering if it is possible to throw a black shadow from the text so that the text would be a little bit easier to read when the background is light? An example would be highly appreciated :)

**Comment by VikAdvani** [comment]
Hi @cjrorvik,
Currently we don't support drop shadows on text. We've added this to our backlog however and plan to add it soon.

For now, a hack that might work to achieve this effect would be do make two text objects one behind the other and slightly offset but black instead of white.

We'll close this issue for now as it'll be tracked here: https://github.com/viromedia/viro/issues/72
