### ISSUE TITLE
Viro compatibility with Create-react-native-app?

### ISSUE THREAD

**Issue by andrwsalcdo** [viromedia/viro#147]
Hi all, 

Was trying to look at the documentation on the website, and I couldn't find anything regarding Viro usage with Create React Native app. 
I'm using Windows. 
If anyone has any insight that would be super helpful. 
I would love to get started. 

Thanks

**Comment by dam00n** [comment]
Hi @andrwsalcdo, we have our own Quick Start guide for ViroReact. Here is the link for Windows -> https://docs.viromedia.com/docs/quick-start-windows

This should get you set up and you can use our Testbed app to developer your AR/VR app in RN. 

Here is documentation on integrating ViroReact with an existing RN project -> https://docs.viromedia.com/docs/integrating-with-react-native-projects

**Comment by achuvm** [comment]
Hi @andrwsalcdo,

You can also "eject" your CRNA application into a React Native project before running through the steps in the Windows quick start (you'd start on the section [Add a Dependency on React Viro ](https://docs.viromedia.com/docs/quick-start-windows#section-add-a-dependency-on-react-viro)).

We require you to either set up a React Native project or eject from CRNA because we require native components and integration (not just JS components).

Thanks,
