### ISSUE TITLE
cant install react-viro on windows 10

### ISSUE THREAD

**Issue by extropy-** [viromedia/viro#156]
so, following the quick start guide here: https://docs.viromedia.com/docs/quick-start-windows

I have had a react server running and talking to my phone.

However when I try the command:
react-native init ViroSample --version=0.49.3

I get the error: The term 'react-native' is not recognized as the name of a cmdlet, function, script file, or operable program.

!? help please

**Comment by achuvm** [comment]
Hi @extropy-,

Looks like our documentation is slightly out of date, please run through the instructions in [**Build Projects With Native Code**](https://facebook.github.io/react-native/docs/getting-started.html#the-react-native-cli) up until the [The React Native CLI](https://facebook.github.io/react-native/docs/getting-started.html#the-react-native-cli) step.

Thanks,

**Comment by extropy-** [comment]
ok! working now, thanks

**Comment by achuvm** [comment]
Glad you got it working!

Let us know if you run into any other issues!

**Comment by extropy-** [comment]
hi achuvm, good morning!

as you mention letting you know about other issues..

[btw im testing on Iphone7, Galaxy S6 and Pixel XL from a windows 10 pc]


(1) the 360 photo doesnt work on the testbed app, i only see the words
'hello world' - on both ios and android.
(2) the other parts of the app are very unstable, almost always crashing on
launch, again on all phones.

(3) the testbed app doesnt work on iphone - but is this because i am
deploying from pc?
Or is it because the port is wrong? React says in console that the port
number (at least for its expo app) is 19000 while the iphone  tells me it
is looking on port 8081. I saw somewhere how to change this but cant find
it now.

(4) a suggestion. There appears not to be a way in your code to disable
GearVR or Daydream mode on the applicable phones. That would be a nice to
have (I know I can do it on the phone)


(4) I cant get the HelloWorldSceneAR running. Ive changed the app.js so
that:
var defaultNavigatorType = AR_NAVIGATOR_TYPE;
but it crashes on launch.


cheers
Robert

**Comment by achuvm** [comment]
Hi @extropy-,

1) That's interesting, on iOS, have you tried shaking the device and tapping "reload" in the test menu? Do you notice if your packager server (it's what you started when you ran `npm start`) is processing a request?

2) That's not we expect to happen, what test scenes are you seeing the crashes in? Are you able to give us crash logs? (on Android devices, you can run `adb logcat` or use Android Studio).

3) When you run the packager server, you should see the following output (it's running the server on port 8081):

```
> AwesomeProject@0.0.1 start C:\Users\AwesomeProject
> node node_modules/react-native/local-cli/cli.js start

Scanning 555 folders for symlinks in C:\Users\AwesomeProject\node_modules (62ms)
 ┌────────────────────────────────────────────────────────────────────────────┐
 │  Running packager on port 8081.                                            │
 │                                                                            │
 │  Keep this packager running while developing on any JS projects. Feel      │
 │  free to close this tab and run your own packager instance if you          │
 │  prefer.                                                                   │
 │                                                                            │
 │  https://github.com/facebook/react-native                                  │
 │                                                                            │
 └────────────────────────────────────────────────────────────────────────────┘
Looking for JS files in
   C:\Users\AwesomeProject

Loading dependency graph...
React packager ready.
```

4) Could you elaborate more about this request? If the application is built for GearVR, the application will run in VR mode the entire time (that's just how Samsung/Oculus built it). For GVR builds, we respect whatever setting the user has set in their Daydream application, if it's in Daydream, then we have to run in VR mode because if we don't Google disables the controller. If it's in Cardboard, then you can use the `vrModeEnabled` prop on the `ViroSceneNavigator` to switch between VR and 360 modes.

5) Is this crash on Android or iOS? If it's on Android, can you confirm you've run through the steps in the "If you're running Android AR" callout on the [Windows Quick Start Page](https://docs.viromedia.com/docs/quick-start-windows). ARCore currently only works on Samsung S8, Pixel (XL), and Pixel 2 (XL) devices.

Sorry about all the issues, we hope to get you to a working state soon!

- Andy
