### ISSUE TITLE
Unsupportewd top level event type onErrorViro

### ISSUE THREAD

**Issue by fadani** [viromedia/viro#172]
Hi!

When I load a `ViroARScene` i get an "Unsupportewd top level event type onErrorViro" red screen error.

Tried with
react-viro 2.3.0 and 2.4.0
react-viro-cli 2.4.0 and 2.4.0
ARCore Preview 2 and ARCore 1.0

It seems that this is not a version dependent thing.

What does this error mean? And how could I get closer to what the cause could be?

Thank you

**Comment by achuvm** [comment]
Hi @fadani,

Are you on React Native version 0.49.3? That's the version that we've tested React Viro against.

The error you're seeing might be related to this [React Native issue](https://github.com/facebook/react-native/issues/16522) that seemed to have appeared with React Native 0.50.X.

Have you tried creating a new project and using our testbed application? The new project should work w/ the `HelloWorldSceneAR.js` scene.

Let us know if that doesn't work for you!

**Comment by fadani** [comment]
Hey @achuvm,

We are using react-native@0.50.3, and in the meantime we found a solution so it works completely fine. We could fix it on our end. It's only that the error message wasn't super helpful. 

Thank you for your answer!

**Comment by achuvm** [comment]
Hi @fadani,

Glad you fixed the issue, the error itself comes from React Native and it's related to how events are "registered" in Java on Android. Its not something we've encountered while running on React Native v0.49.3 so it might be caused by something that changed between that version and v0.50.3.

If you don't mind, could you explain how you fixed it on your end for posterity's sake?

Thanks,

**Comment by AppPear** [comment]
I solved the issue by removing these lines from the code: 
```
explosiveImpulse: {		
    Impulse: 0,		
},
```

I hope it helps!
