### ISSUE TITLE
Urgent: Crash in production

### ISSUE THREAD

**Issue by itchingpixels** [viromedia/viro#180]
Hi!

We have a react-native 0.50.3 app with more than 200k MAUs.
We just released our viro enhanced app, and faced this very frequent crash:
http://crashes.to/s/68be404e1df

`undefined is not an object (evaluating 'n.setJSAnimations')`

the only reference to setJSAnimations is leading us back to viro-react.
Do you have any suggestions how can we mitigate this as soon as possible?

Thank you!

Mark & the Drops team

**Comment by achuvm** [comment]
Hi @itchingpixels,

Do you have any consistent repro steps? 

This function is used in `ViroAnimations.registerAnimations()` which invokes a native module. There might be a race condition in how either we're creating the modules or how React Native is loading the native module.

One way you can possibly mitigate the issue is to delay invoking `ViroAnimations.registerAnimations()` until the `componentDidMount()` in your Viro scenes.

Thanks,

**Comment by itchingpixels** [comment]
Thank you for reacting so quickly, we're rolling this out right now!
Will report back if we have some/enough data!

**Comment by itchingpixels** [comment]
As far as we can tell, this resolved the issue mentioned above, thanks a lot! Closing this now :)
