### ISSUE TITLE
Wrong orientation when built for production

### ISSUE THREAD

**Issue by vysotsky** [viromedia/viro#190]
Hi! I've faced an issue when ViroReact starts rendering content in portrait mode by being in landscape. This problem is not reproduced when my app is built for debug. 
As far as I understand, the problem can be connected with GVR SDK but I cannot check it. Content looks broken - seems that ViroReact tries to show all the content only for one eye (see [the link](https://imgur.com/hhh87dJ)).

The problem persists on the latest sdk (2.4.0).
Affected devices - reproduced on iPhone 6s, 7, X.
Affected iOS version - reproduced on 11.2.1, 11.2.6.

**Comment by vysotsky** [comment]
Just tried rollback to 2.3.0. The issues still persists...

**Comment by manbod** [comment]
Hi @vysotsky ,
Thanks for reaching out! And thanks for providing helpful details on sdk, devices and iOS versions!

You are right in your suspicion on this being connected to GVR SDK. You can refer to these lists of related issues on [googlevr/gvr-ios-sdk github](https://github.com/googlevr/gvr-ios-sdk/issues?utf8=%E2%9C%93&q=landscape+) page.

Does your app have other `UIViewControllers` that have non-VR content? In that case I would assume you need to support all orientations for your app. If that's correct, the easiest mitigation for this GVR bug (this could be by design on their end for reasons unknown to us) is to override `supportedInterfaceOrientations` function in your `AppDelegate.m` file, as follows
```Obj-C
- (UIInterfaceOrientationMask)supportedInterfaceOrientations {
  if(self.isViroSceneDisplaying) { // tweak this to whatever condition you are relying on to detect if a VR scene is rendering
    return (UIInterfaceOrientationMaskLandscapeRight);
  }
  return (UIInterfaceOrientationMaskAll); // Change this to whatever orientation your non-VR content in the app needs to be
}
```
The above function determines what orientation your app supports whereas the orientation in the plist determines which orientation we are allowed to launch into.

We have found the above workaround seems to get the most robust user experience for VR enabled content on GVR. Let us know if this works for you.

I also noticed our documentation [here](https://docs.viromedia.com/docs/integrate-project-with-viro) mentions to rely on `UIInterfaceOrientationMaskLandscapeLeft 
 | UIInterfaceOrientationMaskLandscapeRight`. I think this is a recent change in GVR SDK that we missed updating our docs. I'll update it now. Sorry if that caused any confusion!

Lastly, you can go back up to using 2.4.0 version of ViroReact. This guidance would be the same for both 2.3.0 and 2.4.0 versions.

**Comment by vysotsky** [comment]
Thanks for the response. I have this orientations configured by code whic is similar to samples provided by you. And as I've said, all is ok with my app when it's build for debug. But when I set "Release" configuration, even not archiving, the scenes start being broken. 
I'm trying to investigate if this issue also affects your sample project generated by running ```react-viro init ViroSample --verbose``` but the sample uses 2.2.0 in it. So for now the main trouble is to run this project with the 2.4.0 version because you've changed ```use_frameworks```. I'm going to provide more information soon.

**Comment by vysotsky** [comment]
I spent ages trying to run your sample project :)
But I think I found the root of the issue. The issue appears when:
1. An app has not only one root view controller but also navigation controllers etc. Our app is almost native with one controller which renders react native views so that's our case.
2. You set DEBUG=0. That's a very strange thing.
3. Probably code optimization ```-none``` also makes this behavior exist.
I was only able to fix or probably mitigate this bug by presenting react native inside new UIWindow. Now seems that it works even when I build for Release.

**Comment by manbod** [comment]
Glad you got it working @vysotsky ! 
As regards the `react-viro init ViroSample --verbose` creating sample using 2.2.0, you need to update your `react-viro-cli` to the most recent one. What does `react-viro --version` return for you? If everything is updated correctly it should show the following output
```
== Versions ==
react-viro-cli: 2.4.0
react-native-cli: 2.0.1
react-native: 0.49.3
```
Once you update your `react-viro-cli` to the latest one (`npm update -g react-viro-cli`), your `react-viro init ViroSample` should create the sample using 2.4.0 react-viro, correctly.

Unsure of how your app is structured / app's build settings are configured, but after a fresh `react-viro init ViroSample` I do see DEBUG=1. And code optimization `-none` is set just for Debug, `-Fastest, Smallest` for Release as default but Xcode during ide setup. App developers are free to tweak this to their suiting.

Let us know if you run into orientation issues again after you update your react-viro-cli to 2.4.0.
