### ISSUE TITLE
Crashing on Android <= 6.0 with java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by KimAM** [viromedia/viro#192]
We've gotten alot of the following errors on different Android devices with 6.0 and below:

`dlopen failed: could not load library "libarcore_sdk.so" needed by "libviro_react.so"; caused by could not load library "libcamera2ndk.so" needed by "libarcore_sdk.so"; caused by library "libcamera2ndk.so" not found`

Any idea on how we can solve this?

**Comment by radvani** [comment]
Hi @KimAM, this shouldn't happen, you should be seeing an UnavailableDeviceNotSupportedException instead. Just to verify, are you using the latest version of ViroReact?

The root cause of the issue is ARCore requires Android 7.0 (API 24) and above, in part because it uses the NDK camera (libcamera2ndk.so). 

If you run the [isARSupportedOnDevice](https://docs.viromedia.com/docs/isarsupportedondevice) function as shown in the link, do you still get the error?

**Comment by KimAM** [comment]
Thanks for the reply, we are using isARSupportedOnDevice, but it's too late to do it in Javascript as the app crashes on launch. To fix this we removed 
`new ReactViroPackage(ReactViroPackage.ViroPlatform.GVR)` as a package in MainApplication's `protected List<ReactPackage> getPackages() { }` for all devices below API 24. That fixed our problem. I'll just close this one.
