### ISSUE TITLE
Normal React Native Component Start Page

### ISSUE THREAD

**Issue by myhendry** [viromedia/viro#205]
I am hoping to develop something like your testbed app. It will render a start page (normal react native component) which list the various 360 photos that my users can click to view. When users click on an image, it will then navigate them to another component which shows the 360 photo.

Is it possible with react viro? any sample codes I can refer to if there is any? Thks

**Comment by manbod** [comment]
Hi @myhendry ,
Thanks for reaching out. From what I understand, what you're trying to achieve is definitely possible with ViroReact. For your goals, you could actually start with our [Quick Start guide](https://docs.viromedia.com/docs/quick-start) to get started on a sample ViroReact project. The HelloWorld Scenes that you get at the end of setup (see at 4:33 in the Quick Start video on the above link). 

The `App.js` that we initially provide asks the user to select their experience type (AR or VR), using a normal react native component. In your case it will a list of your 360 photos. And depending on what the user clicked you would pass the user selection to your `InitialVRScene`. This InitialVRScene is pointing to `HelloWorldScene.js` and already contains a `<Viro360Image>. Here you would tweak it so that it relies on props or application state to determine which 360 photo to render. 

For quick reference, following are some of the components you would be working with (all of them included in the hello world examples:
https://docs.viromedia.com/docs/viroscenenavigator
https://docs.viromedia.com/docs/viroscene
https://docs.viromedia.com/docs/viro360image

Cheers!
