### ISSUE TITLE
ViroScene - not capturing any touches, clicks, ... and camera is not used even if it is active

### ISSUE THREAD

**Issue by dominicrico** [viromedia/viro#210]
Hi, 

In your react-viro lib within a Viro3DNavigator containing a ViroScene I'm not able to detect any clicks, touches, ... on an object within that scene.
I expected that a normal click would be triggered if the user clicks on an Object within that scene.

Is it true that the camera is also not working in an ViroScene? My rotation and position is totaly ignored.

Thank you in advance

**Comment by manbod** [comment]
Hi @dominicrico ,
Thanks for reaching out. Would you mind sharing your code around how you are handling clicks, touches, etc.? I just tested internally, and all click / drag events seem to be working as expected in `v2.5.1` for `Viro3DSceneNavigator`. Let us know and we can take a deeper look at why these click events aren't working for you.

And regarding setting camera rotation and position in a `ViroScene` used in a `Viro3DSceneNavigator` - this seems to be a legit bug in `ViroReact`. Great catch on the bug! Sorry for the trouble though. We are looking into fixing this for an upcoming release. 

Thanks!

**Comment by manbod** [comment]
Hi @dominicrico ,
Were you able to unblock yourself wrt. touch events and camera? We did some more digging with the camera bug, turns out was a miss on our part when we tested it 5 days ago. It is in fact **working** as expected. Let us know if this is still not working for you. If not, then getting some code snippets from you should help in diagnosing why are you seeing these issues.

Good luck!

**Comment by dam00n** [comment]
Closing this issue as can't repro. Please reopen if you are still experiencing issues with the requested additional info and we can look into it further.
