### ISSUE TITLE
Follow the camera/phone

### ISSUE THREAD

**Issue by peterel** [viromedia/viro#213]
Hi,

This is a question rather than a bug. Im trying to get a 3D-object to follow the camera. My idea to do this is to register an animation and have its properties updated as per where the camera/phone is in x,y,z. 

Ive have a 3D object, I have an animation that can move and I have been able to use the getCameraOrientationAsync() to get the camera position...but not continuously as I move around. Do you have any tips on how I can go about to continuously get the camera x,y,z and update an animations properties accordingly?

Thanks.

Best,

Peter

**Comment by achuvm** [comment]
Hi @peterel,

You can simply loop and run `getCameraOrientationAsync()` every 100 ms. See the below code:

```
componentDidMount() {
  this._interval = setInterval(() => {
    // Your code here
  }, 100); // 100 ms
}

componentWillUnmount() {
  clearInterval(this._interval);
}
```

**Comment by peterel** [comment]
@achuvm Awesome, thanks. 

I get the position continuously now but cant seem to update the position-property of the animation on the fly. I see an chaining and interrupting animations but no update. I was hoping to just use the position globally as below but no dice. Any idea on how I can update the animation to actually follow the camera/phone?

```
ViroAnimations.registerAnimations({
    animateImage:{properties:{positionX:global.positionX, positionY:global.positionX, positionZ:0, opacity: 1}, easing:"Bounce", duration: 1000},q
}); 
```
Thanks again.

Peter

**Comment by achuvm** [comment]
Hi @peterel,

As a sanity check, are you making the call to `ViroAnimations.registerAnimations()` within your callback function?

You may have to register a different animation each time because of how React works in that if a property doesn't actually change, then the underlying components don't get the update (ie. in this case your animation is always called `animateImage`).

Although, if your interval is 100ms (10 times a second), would simply setting position give you the same desired result as animating the object?

**Comment by peterel** [comment]
Hi @achuvm,

Many thanks for your help. I had a bug in my code, seems to work fine-ish now. Closing.

Peter
