### ISSUE TITLE
ViroARImageMarker Unusably Laggy

### ISSUE THREAD

**Issue by timnlupo** [viromedia/viro#215]
Hi everyone,
I'm trying to use a `ViroARImageMarker` in my AR experience. My code is essentially the same as the tutorial and below.
```
<ViroARImageMarker target={"targetOne"} >
   <ViroBox position={[0, .25, 0]} scale={[.5, .5, .5]} />
</ViroARImageMarker>

ViroARTrackingTargets.createTargets({
  "targetOne" : {
    source : require('./res/target2.jpg'),
    orientation : "Up",
    physicalWidth : 0.8 // real world width in meters
  },
});
```
The object tracks but is unbearably laggy, nothing like the videos I've seen from other people. This project was built in Xcode (not simulator) and I am using an iPhone X on iOS 11.3. Any ideas?

[Here](https://www.dropbox.com/s/haj55org8kd4wt3/IMG_1165.mov?dl=0) is a video of what is happening.

**Comment by dam00n** [comment]
ARKit will continue to look for the target image and return new anchors as they are found. Try setting pauseUpdates to true once an anchor is found. (You can optimize this further by pausing after 3-5 anchors because the first one might not always be the optimal one.)

getInitialState: function() {
    return {
      pauseUpdates : false,

...

 <ViroARImageMarker target={"tipi"} onAnchorFound={this._onAnchorFound} pauseUpdates={this.state.pauseUpdates}>

...

_onAnchorFound() {
    this.setState({
      pauseUpdates: true,
    })
  },
});

**Comment by timnlupo** [comment]
Yes, this worked! I think it was a combo of my size being too big and my camera being too close, works now with or without the anchor fix. Thank you.
