### ISSUE TITLE
ViroVRSceneNavigator.onExitViro method not called

### ISSUE THREAD

**Issue by grahamyesfit** [viromedia/viro#230]
react: 16.2.0
react-native: 0.55.2
react-viro: 2.5.1
Device: Pixel 2 

I've constructed a basic scene, and I've included the onExitViro property on the ViroVRSceneNavigator component. My understanding is that the method I supply will be called when the user taps the "X" on the Viro display.

However, the method is not called. I see the "X" light up when I tap it, but nothing happens. When I tap the gear icon, the VR settings page correctly comes up.

Here's my code:

```
class NativeViro extends React.Component {

	_onExitViro = () => {
		console.log('_onExitViro');
		//this.sceneNavigator.pop();
	}

	render() {
		return (
			<ViroVRSceneNavigator
				ref={ref => this.sceneNavigator = ref}
				onExitViro={this._onExitViro}
				apiKey="..."
				initialScene={{
					scene: () => (
						<ViroScene>
							<Viro360Image
								vrModeEnabled={true}
								stereoMode="TopBottom"
								rotation={[0, 180, 90]}
								source={{ uri: "..." }} />
							<ViroText text="Hello World!" width={2} height={2} position={[0, 0, -2]} style={styles.helloWorldTextStyle} />
						</ViroScene>
					)
				}} />
		);
	}
}
```

**Comment by manbod** [comment]
Hey @grahamyesfit ,
Thanks for reaching out. I just internally tested and confirm onExitViro() property is working on all of our `Viro(x)SceneNavigator`s as intended. I am a little unsure if you included your entire class file or just the relevant code snippet. My initial guess is, since this is ES6, you probably need to bind `_onExitViro()` to `this` in the class constructor prior to invoking it in the render() function. As `this._onExitViro = this._onExitViro.bind(this);`

If that isn't the case, we'll probably need a little more info from you for us to be able to dive deeper / reproduce on our end. Are you trying to run this app in debug or release? In debug, this should most likely result in a red screen with something on the lines of "this._onExitViro() is undefined" error. Let us know and we can dig a littler deeper.

Also, another thing I noticed - although this should be unrelated to the problem you are facing, you are using `react-viro: 2.5.1` with `react-native: 0.55.2`. From our release page -> https://docs.viromedia.com/docs/releases, up until `v2.5.1` we were compatible with `react-native: 0.49.3`. We just released a `v2.6.0` yesterday that we have internally tested with `react-native: 0.55.1` before releasing. While older or newer versions of react-native may work with Viro, there may be issues or differences that cause ViroReact to not work properly with older or newer versions of react-native.

Thanks!

**Comment by grahamyesfit** [comment]
Thanks for your reply, @manbod . 

I upgraded to `react-viro 2.6.0` and I can confirm that onExitViro is working as expected.

Incidentally, I'm using arrow syntax to auto-bind the method, so there's no need to manually bind it in the constructor.

Keep up the good work, this library is awesome. I'm impressed with your responsiveness to GitHub issues, too.

**Comment by MinhazMM** [comment]
I can't seem to get it working on Android devices, but for iPhone the onExitViro method gets called and on iPhones it's showing a left arrow and on Android devices it is showing "X". 

My dependencies are as follows:
```
    "expo": "^36.0.2",
    "expo-cli": "^3.16.1",
    "expo-file-system": "^8.1.0",
    "react": "16.8.3",
    "react-native": "0.59.9",
    "react-native-paper": "^3.6.0",
    "react-native-responsive-fontsize": "^0.4.3",
    "react-native-responsive-screen": "^1.4.1",
    "react-native-unimodules": "^0.7.0",
    "react-native-vector-icons": "^6.6.0",
    "react-viro": "2.17.0",
    "rn-bottom-drawer": "^1.4.3"
```
And here is the code I have for the onExitViro

```
  _exitViro (){
    this.setState({
      navigatorType: "UNSET"
    })
  }
```

and I am calling it on the ViroVRSceneNavigator as
```
onExitViro={this._exitViro.bind(this)}
```
