### ISSUE TITLE
Hiding Objects behind a wall.

### ISSUE THREAD

**Issue by parideis** [viromedia/viro#261]
Hello,

is there a possibility to hide Objects if they are behind a (physical) wall?
Like a ViroQuad in the world, which is invisible, but still blocks Objects behind it.

**Comment by VikAdvani** [comment]
Hi @parideis 
Currently there is not a way to do this. However we understand the use case and will allow transparent surfaces that occlude for AR in a future release. For now, if you know the color of the wall you can have a texture over the quad(not ideal). We'll update this issue once it's ready :)

**Comment by parideis** [comment]
@VikAdvani Thanks for the answer. Sadly our walls aren't in a solid color. 
Anyhow I really like what you guys already accomplished and look forward for even more awesome features! :)

**Comment by rbnitish** [comment]
@VikAdvani Can we say, library still doesn't support obstacle detection. Not sure, but what I observed is, supposed we place AR Text at some far point with -z value, and if I place my hand in front of camera, that text still appears over my hand, seems like depth isn't recognised here. In this case, that AR Text (object) should be hidden due to this obstacle. Maybe I'm missing something, due to new to this library. But I compared it with Apple's View in AR feature, that gives me hint for this. 
![IMG_1874](https://user-images.githubusercontent.com/85098671/138170350-b6c404e2-b237-4ddc-81c8-e26efcf57ece.JPG)
