### ISSUE TITLE
Unable to use ViroCamera in ViroARScene

### ISSUE THREAD

**Issue by leejooho388** [viromedia/viro#275]
Hello, I am using react-viro 2.6.1.
I am working on an app that uses Viro React AR.
I was looking into setting the camera position and rotation using ViroCamera but I kept getting errors claiming that ViroCameraModules isn't defined.

I investigated deeper and found that ViroArScene.js uses ViroCameraModule as a variable but it isn't declared.

`cameraDidMount: function(camera) {
        if (camera.props.active) {
          ViroCameraModule.setSceneCamera(findNodeHandle(this), findNodeHandle(camera));
        }
      }.bind(this)`

I looked into ViroScene.js and I noticed that they use NativeModules.VRTCameraModule instead.
`cameraDidMount: function(camera) {
        if (camera.props.active) {
          NativeModules.VRTCameraModule.setSceneCamera(findNodeHandle(this), findNodeHandle(camera));
        }
      }.bind(this)`

Can I just replace ViroCameraModule in ViroARScene.js with NativeModules.VRTCameraModule and have it function the same?

Thank you.

**Comment by ViroHalliday** [comment]
Hi @leejooho388 ,
Thanks for reaching out. What you are seeing in ViroARScene is actually by design. If you look [here](https://docs.viromedia.com/docs/augmented-reality-ar), in AR the platform responds to the user's rotation and position as they move about the world by moving the physical camera on device. The camera will remain at `[0,0,0]`. 

Unsure of what your use case is, but in AR we'd recommend changing the object's position and rotation relative to the camera, instead of the other way around.

Thanks

**Comment by manbod** [comment]
Hi @leejooho388 ,
Thanks for reaching out. What you are seeing in ViroARScene is actually by design. If you look here, in AR the platform responds to the user's rotation and position as they move about the world by moving the physical camera on device. The camera will remain at [0,0,0].

Unsure of what your use case is, but in AR we'd recommend changing the object's position and rotation relative to the camera, instead of the other way around.

Thanks

**Comment by leejooho388** [comment]
Hello,

Thank you for the response. I understand what you mean.
I will attempt to use something else.

Thank you.
