### ISSUE TITLE
resources or materials not applying on VRX file

### ISSUE THREAD

**Issue by QQizi** [viromedia/viro#278]
I'm using a VRX file of my own but i can't figure out how to play texture or materials on it.
I'v try with the resources parameter by passing an diffuse png as well as tried a materials with createMaterials.

Is there something to do in the FBX file to allow resources or materials to be apply ?

I tried to replace the resources of your example "ARPosterDemo" but nothing changes.
I then tried to remove all the resources of the same example, the black panther caracter still have all his texture visible.
Is the resources parameter even works ?

Thx for your help

**Comment by QQizi** [comment]
We finally figured it out. The FBX need to be exported in V6.

The resources or materials parameters are not working at all tho. I can't apply a basic "red" material to the vrx

**Comment by manbod** [comment]
Hi @QQizi ,
Can you share your code snippets for the relevant VRX files? We are unable to produce this bug on our end - neither are our other developers working with Viro. It would be helpful if we could take a look at your code to see what issues you are facing. Would need a little more info in order to help you guys out:
1. What happens when you apply a basic red material? Do you get an error? Or nothing changes? Or do you not see your vrx at all?
2. Do you have lights in your scene? What lights do you have? Can you include that in your code snippet also?
3. How are you creating your materials? Do you have a lighting model included in it? Can you paste your code snippet for where you create this material as well?
4. Are you trying this in debug version of the app, or release? Or through our testbed app? What version are you on?

A quick note on the `resources` parameter, since you mentioned *tried to replace the resources of your example "ARPosterDemo" but nothing changes.* -> If you look at our [documention](https://docs.viromedia.com/docs/viro3dobject) on `resources`, it's only required in "release" version of the app, so that react-native's *packager* can include them in the bundled app. So the correct way of adding materials is by using `createMaterials`.

Do share your code snippet (including your `Viro3DObject`, any lights in the scene, and your `ViroMaterials`) and we'd be happy to help you out.

Thanks,
Manish

**Comment by QQizi** [comment]
Hi @manbod,

Thank you for your answer. Do you think it's gonna change in a near future ? Using custom materials just like you did in the example with the Tesla car would be very interesting.

**Comment by manbod** [comment]
Hi @QQizi ,
Currently we don't have a timeframe for when that would change in the future. The limitation comes from `FBX` model format, where the materials are declared in the model description itself. The example with Tesla car uses an `OBJ` models - which allow changing materials dynamically.

**Comment by VikAdvani** [comment]
Closed due to inactivity.
