### ISSUE TITLE
[AR] Make 3D model always visible

### ISSUE THREAD

**Issue by parideis** [viromedia/viro#280]
Hello,

I want to create an indicator (like a 3D compass) which points to an 3D model in the AR Scene.
The indicator should be always visible. 
My Idea is to get the camera orientation & position with `async getCameraOrientationAsync()` and to update the position of the indicator.

1. Is this the best way to do it, especially regarding performance ?
2. How do I exactly use `getCameraOrientationAsync ` Method?

**Comment by parideis** [comment]
Just found some sample Code over here:
https://github.com/viromedia/ViroARSampleApp/blob/master/js/ARHitTestSample.js
I'll try it out.

**Comment by parideis** [comment]
I get the current camera object and save it in `camera`.
This is how I set the position of the 3D Model:
`this.state.camera.position[0] + this.state.camera.forward[0] + this.state.camera.up[0],
this.state.camera.position[1] + this.state.camera.forward[1] + this.state.camera.up[1],
this.state.camera.position[2] + this.state.camera.forward[2] + this.state.camera.up[2]`

But it doesn't work like I excepted. Sometimes the model is visible and sometimes not.
I think it depends how the device is orientated when the app starts.

Is there an better approach to make a model always visible in AR?

**Comment by manbod** [comment]
Hi @parideis ,
I quickly tested a sample here internally. To position the object infront of the camera, the correct math would be something like this`[this.state.camera.forward[0] * 3, this.state.camera.forward[1] * 3, this.state.camera.forward[2] * 3]`. Where this positions the object 3 meters infront of the camera along the forward vector. You could change the 3 to however far / near you want your object to be.

Another recommendation would be to rely on `setNativeProps` to change the object's position rather than state here, for better performance. Since setting state at a high frequency will be detrimental to performance, as each `setState` causes a call to `render()` function.

**Comment by VikAdvani** [comment]
Closing.
