### ISSUE TITLE
Is it possible to get height and width of ViroARImageMarker?

### ISSUE THREAD

**Issue by bryantAXS** [viromedia/viro#311]
I'm trying to use an image maker to locate an image, and after detection, place a video exactly on top of the image itself. I noticed that the anchor variable provided after detection doesn't provide width and height.

Is this something that's possible currently?

**Comment by achuvm** [comment]
Hi @bryantaxs,

Currently the way that the ViroARImageMarker works is that the developer knows the physical width/height of the marker and provides it as a parameter into the component itself (https://docs.viromedia.com/docs/ViroARImageMarker). As such, it is assumed that the developer knows the physical width/height of their marker in the real world and the platforms (ARKit/ARCore) simply return the position (center) of the marker. 

Let us know if this makes sense. 

Thanks,

**Comment by achuvm** [comment]
Hi @bryantaxs,

Because this is AR, you simply need to place the object in the world w/ the same physical dimensions and it'll "be" the same size as the marker.

Ie. If the poster is 5 meters from you with a size of 2x1 meters. Then if you added an object of size 2x1 meters(the Viro units are in meters) to your virtual world 5 meters from the camera. Then it would "cover" your target. 

Although our ViroARImageMarker makes it easier in that you simply have to place the object within the component and it'll be positioned correctly "on" the marker.

**Comment by bryantAXS** [comment]
Ah ok, that makes sense! I think the "problem" here was more so me just wrapping my head around things. Thank you!
