### ISSUE TITLE
How much drift is expected and what contributes to more drift vs less?

### ISSUE THREAD

**Issue by bryantAXS** [viromedia/viro#329]
I've got a few different AR demos we're working on. The majority of the 3DObjects/Videos/Models have some amount of drift. I'm wondering how much is to be expected and what are the various contributors to drift?

[In this video](https://cl.ly/2j2z0V0j2U1n), I'm using a Image Marker to displaying a ViroVideo component ontop of the recognized image. When I move around, the video doesn't stay consistently on top of the image.

Here's the code for that example:

```
<ViroARImageMarker
          onAnchorFound={this._onAnchorFound}
          target={"targetOne"}
          pauseUpdates={this.state.pauseImageMarkerUpdates}>

          <ViroNode ref="objectNode" position={[0, 0, 0]} rotation={[-90, 0, 0]} dragType="FixedToWorld" onDrag={()=>{}}>

            <ViroVideo
              source={require('../../assets/videos/mural.mp4')}
              width={0.215}
              height={0.2794}
              />

         </ViroNode>

        </ViroARImageMarker>
```

[In this example](https://cl.ly/3T0w3g2L1D3M), when a load a 3DObject into the view, as I move around the object, slight bumps and twitches can be seen. Again subtle, but obviously it would be great to mitigate.

Here's the code for that example:

```
<ViroARImageMarker
          onAnchorFound={this._onAnchorFound}
          target={"targetOne"}
          pauseUpdates={this.state.pauseImageMarkerUpdates}>

          <ViroNode
            ref="objectNode"
            >

            <Viro3DObject
             source={require('../../assets/objects/vianneyhouse.glb')}
             onLoadStart={this._onLoadStart}
             onLoadEnd={this._onLoadEnd}
             onError={this._onError}
             onClick={this.props.onObjectClick}
             scale={this._getAdjustedScale()}
             position={this._getAdjustedPosition()}
             type="GLB" />

         </ViroNode>

        </ViroARImageMarker>
```

In this [thread](https://github.com/viromedia/viro/issues/262), the `pauseUpdates` attribute is mentioned to help with drift, which I'm using, but obviously doesn't totally fix the problem.

I also noticed you were adjusting the `position` and `scale` of the objects being added. How do those properties relate to drift?

**Comment by Tamiyadd** [comment]
Hi @bryantAXS i'm having the same problem. Sometimes the Node is also rotated in strange way. I think it depends on how the marker is found. 
Hope to find a solution because it's annoying

**Comment by achuvm** [comment]
Hi @bryantAXS,

I took a look at your first video, and it looks like what's actually happening is that your virtual component is being rendered "behind" your physical component. As such, this is causing the virtual component to move less relative to the camera than your physical one. This usually happens to image markers whose targets have a slightly off `physicalWidth` (refer to [ViroARTrackingTargets](https://docs.viromedia.com/docs/viroartrackingtargets)). 

In your second video, the fidgeting in the model seems to be a result of poor camera tracking (the room looks a bit dim and the table is featureless) as opposed to poor image recognition (to test this, place another object in the scene *not* tied to a marker and see if it too exhibits the fidgeting). 

As for the `pauseUpdates` property, this is advised if you plan on using `ViroARPlane` components because both their `rotation` property get updated as you move around, so if you were to place an object within a `ViroARPlane`, it would continue to rotate as the extent of the plane is being discovered. For a `ViroARImageMarker` however, you would want at least a few updates in case the first "find" of the marker isn't a very accurate one, or simply leave `pauseUpdates` to false as it will recalibrate the position of the marker even if you experience camera drift.

In that thread you were looking at, the person didn't properly `scale` and `position` their object so the portal they were using looked right until they started moving because the object was positioned about 1-2 feet into the ground. This is probably what is happening with your first video. If you walk all the way to the "side" of the image, you might notice that your virtual image being positioned "further" from your original position than the physical one.

Let me know if you still are seeing issues, thanks!

**Comment by Tamiyadd** [comment]
@achuvm as you can see I'm having problems with stability too
https://www.dropbox.com/s/4w3an64xfrr4ctx/UKCT5304.MP4?dl=0
how can i make the image to stand attached to the marker? 

```
<ViroARImageMarker
              target={arVideoMarker}
              key={arVideoMarker}
              onAnchorFound={anchor => _this.arVideoFound(anchor)}
              onAnchorUpdated={anchor => _this.arVideoUpdated(anchor)}
              pauseUpdates={false}
              // pauseUpdates={_this.state.pauseArVideoUpdates}
            >
              {_this.state.foundAnchor && (
                <ViroImage
                  width={0.09}
                  height={0.09}
                  position={[0, 0, 0]}
                  rotation={[-90, 0, 0]}
                  source={require('../../../../assets/images/ar_targets/ar_video.png')}
                />
              )}
            </ViroARImageMarker>
```

**Comment by achuvm** [comment]
Hi @jonnyscholes,

Thanks for the heads up, and yes, since we do use ARCore/ARKit, this tool should help with Image Recognition on Viro.

I'll go add it to our documentation!
