### ISSUE TITLE
Objects slide around and are not anchored in real world

### ISSUE THREAD

**Issue by itsthechad** [viromedia/viro#331]
I'm impressed with the feature set, documentation, and demo videos of ViroReact, but the actual implementation is not very solid for me so far.

I've been running the demo code and am seeing the 3d objects slipping and sliding around the world. My understanding is that they should be able to be attached to a plane and then remain in position (within reason) at that point. Instead, the objects move quite a bit as I walk around and change orientation.

[Here is a video which shows what I'm seeing.](https://drive.google.com/open?id=1B5Hk0hqAxnHipojig1Tppmkgz_3RgX2j) In it, I'm running the viro sample app (found here: https://github.com/viromedia/viro). The only changes I've made were to add my API key and change to the  ARSimpleSample demo. In the video, I move the emoji to the table, and then it flies away as I walk around the table. I then move the soccer ball to the table, and it scoots towards the edge as I walk around the other way (meanwhile, the emoji flies back in).

Questions: Are my expectations incorrect for these demos? Should I be seeing the objects be better anchored in the real world? Am I doing something wrong that you can see?

Thanks,
Chad

Edit: I am on an iPhone 6s Plus, using the Viro Media app.

**Comment by manbod** [comment]
Hi @itsthechad ,
Thanks for checking us out and for reaching out to us. The reason why you are seeing your 3D objects slipping / sliding can be pointed to how underlying ARKit detected planes in your surrounding. In the video when you drag the emoji to the table -> ARKit did not detect your table surface as plane, or if it detected it, with your drag it thought your intent was to move it along your floor instead of jumping from floor plane to another. As a result, your dragging actually moved the emoji really far away from the camera along the plane it detected on your floor. Since after the drag, the emoji is "really far away", on the floor, it appears to be moving on top of the table, due to perceived distance. The same can be said about the soccer ball. It didnt go as far as the soccer ball, but from what I can see in the video, it still didnt jump from floor plane to the table plane. You can test it out by giving colors to the detected planes `ViroQuad` . You can test it out be standing a little closer to the table so that the objects are placed on the table when "Initializing AR..." message is showing. See how anchoring works then. Try to move the objects only along the table, and then try moving the objects "off the table" and see how that works out. 
All of the above boils down to -> In some scenes it's hard for ARKit to understand plane boundaries, and moving an object from one plane to another can be finicky at times. Try dragging the objects along just a single plane to see if you get objects anchoring better to the real world.

You can also try our Figment AR App from App Store https://itunes.apple.com/us/app/figment-ar/id1270018902?mt=8. Which is basically the same code for object placement, as the sample code we provide, but in a full fledged app to test out how the experience works / breaks for you.

Thanks,

**Comment by itsthechad** [comment]
Hi @manbod,

Thanks for the response. I am having better success when viewing objects on the floor, as opposed to the table. So it sounds like ARKit is having trouble with the table.

Can you tell me how to give colors to the detected viroquads, as you suggested?

Thanks,
Chad

**Comment by manbod** [comment]
Hi @itsthechad ,
Good to hear! If you look at our [sample code](https://github.com/viromedia/viro/blob/master/js/ARPhysicsSample/BasicPhysicsSample.js) for `ARPhysicsSample`, you'll see how to associate a `ViroQuad` with detected `ViroARPlane`s and how to give color to the ViroQuad using `materials` property. Try it out by changing the `scene: arScenes['ARSimpleSample'],` at line 55 of `App.js` to `scene: arScenes['ARPhysicsSample'],`. The physics sample also allows you to drag the basket ball along the plane with physics enabled on the scene. That should be a good example too. Thinking about the issues you were experiencing earlier, we should perhaps enable adding colors to the detected planes as a debugging functionality to the basic sample code (or perhaps to the platform) itself. We'll circle with the team and add it in the near future. 

You can find our documentation for `ViroARPlane`, `ViroQuad` and Materials on the following pages:
https://docs.viromedia.com/docs/viroarplane
https://docs.viromedia.com/docs/viroquad
https://docs.viromedia.com/docs/materials

Let us know if you have any questions.

**Comment by itsthechad** [comment]
Thanks @manbod. I appreciate the help.

**Comment by lessp** [comment]
> Thinking about the issues you were experiencing earlier, we should perhaps enable adding colors to the detected planes as a debugging functionality to the basic sample code (or perhaps to the platform) itself. __We'll circle with the team and add it in the near future.__

Hey all, was this ever added?
