### ISSUE TITLE
How to do AR like Living Wine labels ?

### ISSUE THREAD

**Issue by mkharibalaji** [viromedia/viro#339]
Hi Guys,
         How todo a AR app like the one in this link on the bottle via Viromedia Framework ?

https://tactic.studio/living-wine-labels/

**Comment by dam00n** [comment]
Hi @mkharibalaji, you can use our ARCarDemo as a template. The Wine Label app is an example of image recognition. Rather than use the entire wine label as the marker, you probably want to use a cropped image of a portion of the label so that it is flatter and easier to track. You can use a curved OBJ and apply a video texture on it, so it matches the curve of the bottle (example code below). You you could try using alpha video -> https://docs.viromedia.com/v2.7.3/docs/video#alpha-video-chroma-key-filtering

```<ViroARImageMarker target={"label"} onAnchorFound={this._onMarkerFound}>
        <ViroNode position={[0, 0, -.008]} rotation={[-90, 0, 0]}>
          <Viro3DObject
            source={require('./res/winebottle_label.obj')}
            materials="bottle"
            type="OBJ"
            scale={[.28,.28,.28]}
            />
          <ViroMaterialVideo material="bottle" paused={this.state.pauseVideo} loop={true} />
        </ViroNode>
        </ViroARImageMarker>```

**Comment by mkharibalaji** [comment]
Thanks @dam00n Will try and let you know.

**Comment by mkharibalaji** [comment]
Hi @dam00n It's working and got issues on marker traking which i will raise it as a separate issue.We can close this issue
