### ISSUE TITLE
It doesn't work on samsung j7 prime and samsung j2 phones

### ISSUE THREAD

**Issue by dekemega** [viromedia/viro#34]
09-30 01:27:23.227 8867-8978/com.virosample E/AndroidRuntime: FATAL EXCEPTION: GLThread 288
                                                              Process: com.virosample, PID: 8867
                                                              java.lang.IllegalArgumentException: eglChooseConfig failed
                                                                  at android.opengl.GLSurfaceView$BaseConfigChooser.chooseConfig(GLSurfaceView.java:853)
                                                                  at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1024)
                                                                  at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1401)
                                                                  at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

**Comment by dthian** [comment]
Hi Deke,
To diagnose the issue, could you please provide:
1) What kind of Android phone, and it's model.
2) The Android OS version that is being run on that model.
3) Repro steps on what you were doing leading up to the crash. The more information you can give us, the better.
4) If you were attempting this on the Viro Testbed app, or with your own Android built native application with Viro.

**Comment by dekemega** [comment]
i test it on android emulator with android 7 on it and on samsung j7 prime runs android 6.0.1 and samsung j2 runs android 5.1
i couldn't download your testbed app because of " your device isn't compatible with this version"

![screenshot_20171001-095025](https://user-images.githubusercontent.com/23610404/31052470-36f3fca6-a68e-11e7-86b7-7b78d26ff37b.png)

**Comment by dthian** [comment]
Thanks Deke,

"i test it on android emulator with android 7" - Unfortunately we do not currently support the android emulator at the moment. Although this is something we might consider in the future (if there's a large demand for it), there's also the consideration of performance cost with 3D rendering through the emulator (Even today with just a simple Android application, there is a noticeable lag). 

"i couldn't download your testbed app because of " your device isn't compatible with this version"" - by this do you mean you couldn't download the testbed app on your samsung j7 and  samsung j2 phones? Hopefully, that shouldn't be happening as both should satisfy the app's requirement of Android 5.0 and up. 

Also, have you followed the instructions at http://docs.viromedia.com/docs/installing-viro-android when setting up Android studio with Viro? I would also recommend installing the ViroApp if you can over this option as it is much easier and faster to get setup.

Thanks!

**Comment by dekemega** [comment]
yes i tried to download testbed app from j7 prime and it didn't allow me so i tried to make a virosample app and i follow the instruction to integrate it with android studio project after that i get this error
![clipboarder 2017 10 03](https://user-images.githubusercontent.com/23610404/31122772-d0ee2648-a845-11e7-81f4-c302bb3335f7.png)
![clipboarder 2017 10 03-002](https://user-images.githubusercontent.com/23610404/31122782-e3984b5c-a845-11e7-9cb6-ca0fe1ba452b.png)

**Comment by dthian** [comment]
Thanks Deke, Unfortunately it seems like Google Cardboard does not support samsung j7 prime and samsung j2 phones. This is because these phones are missing the gyroscope sensor that GVR requires to function [1][2]. As such, the Google store displays "Your device isn't compatible with this version" error when downloading the Viro Media application. My guess is that even if you were to forcefully compile an apk to install irregardless of the limitation warnings, GVR itself would yield undesired results and possibly crashes. 

[1] - https://productforums.google.com/d/msg/play/hEwdxDtjPDw/-GG0uYfJDQAJ
[2] - https://support.google.com/cardboard/answer/6295046?hl=en

**Comment by dekemega** [comment]
Thank you very much ...
