### ISSUE TITLE
ViroARScene has no propType for native prop VRTARScene.onCameraTransformUpdateViro

### ISSUE THREAD

**Issue by aodreman-logoscorp** [viromedia/viro#345]
Hi, I just created a new project using **react-viro init myApp**, and everything went fine, I opened the App.js and pasted my API Key, then went to the terminal and ran npm start, everything seems fine so far. Then I opened the Viro Media App on my iPhone 8+ (iOS 11.4) and entered the IP address of my machine, next I got a red screen, with the following message.

Error: `ViroARScene` has no propType for native prop `VRTARScene.onCameraTransformUpdateViro` of native type `BOOL`

I have been searching for a solution but I can not find out what is happening, any help would be appreciated.

npm: 6.1.0
node: 10.5.0
react: "16.3.1",
react-native: "0.55.1",
react-viro: "2.7.1"

Thanks.

**Comment by manbod** [comment]
Hi @aodreman-logoscorp ,

Thanks for reaching out. Our first guess would be a version mis-match between your react-viro version in node_modules (2.7.1 from your post above) and our Test Bed (Viro Media app) on your iPhone (guessing this is at 2.8.0). We just release v2.8.0 yesterday. If you look at the bottom of the black screen in the app where you enter your IP address, it should tell you what version of react-viro it's expecting. 

Steps to fix your current project -> edit your package.json to point to `react-viro: "2.8.0"` and re-install your node_modules.

Also make sure you go through our update instructions here https://docs.viromedia.com/docs/releases so that future `react-viro init <project-name>` does not cause you similar troubles.

Hope this helps. Let us know if you run into some other issues.

Thanks,

**Comment by aodreman-logoscorp** [comment]
Thanks, that was precisely the problem. Great support guys keep it going!
