### ISSUE TITLE
[Question] Set up android studio with viro react 

### ISSUE THREAD

**Issue by HLneoh** [viromedia/viro#349]
I want to set up android studio with viro react for Hello World sample project. I have tried to modify my Android gradle and manifest files. However, I am facing two problems. 

1. I cannot find "a/android/app/src/ovr/AndroidManifest.xml" in the Hello World project folder. I cannot add the code as shown in below to the file. How can I solve this problem?
![image](https://user-images.githubusercontent.com/25906607/42408446-6c32bd88-81ff-11e8-8305-490c81db4f04.png)

2. I have tried to remove the red lines and add the green lines in my gradle file (Except for the code in question 1 above). When I tried to sync my project, it fails to sync the project and appears the messages below.

![image](https://user-images.githubusercontent.com/25906607/42408454-743f8aa6-81ff-11e8-8c8b-142c9fa0980d.png)

When I tried to upgrade the plugin to version 3.1.2, it appears the error as below.

![image](https://user-images.githubusercontent.com/25906607/42408457-7d6e9e5a-81ff-11e8-8abf-71cb2e75d420.png)

Can somebody help pls?

**Comment by manbod** [comment]
Hi @HLneoh ,

For your 1st question - The file to change is at path `android/app/src/ovr/AndroidManifest.xml`. The `a/` is added by git while creating the diff. It's a comparison between "a" and "b". Disregard them in the path when trying to find the file paths from that diff.

For your 2nd question - What version of Android Studio are you using? If you are seeing this error with Android Studio 3, can you try restarting your android studio? Also, what are the contents of your `<your-project>/android/build.gradle` ? They should be something on the lines of 

```
allprojects {
    repositories {
        mavenLocal()
        maven {
            url 'https://maven.google.com/'
        }
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
```
The error that you are seeing *Gradle DSL method not found: google()* makes me believe you have something on the lines of 
```
allprojects {
    repositories {
        ...
        google()
        ...
    }
}
Change the `google()` to `maven { url 'https://maven.google.com/'}` before updating your Android Studio and hit sync.

Let us know if that works for you,

Thanks,
-
Manish

**Comment by manbod** [comment]
Hi @HLneoh ,
Sorry for the delayed response here. Are you still running into this issue?
For the missing `android/app/src/ovr/AndroidManifest.xml` file, actually the the change in the [gist](https://gist.github.com/achuvm/fe0136818158bec2cdf4d1cd11053f6d) means to add this file. In a git diff gist something like `--- /dev/null +++ b/android/app/src/ovr/AndroidManifest.xml`, `/dev/null` means there was nothing before, add the file mentioned in the `+++ b`. Easiest way to change this would be create a file at `android/app/src/ovr/AndroidManifest.xml` and paste the contents from the [AndroidManifest.xml](https://gist.github.com/achuvm/fe0136818158bec2cdf4d1cd11053f6d#file-androidmanifest-xml-L1-L9) at the bottom of the gist file above. Additionally, you only need this change if you are trying to build your app for Samsung Gear VR platform. Otherwise you don't need this change.

For your second problem -> I just ran through our instructions for setting up Android Studio on Windows. We are missing adding the `maven` step I mentioned earlier in this thread. While we are updating the gist file, you can add it to your project as follows:
Open the build.gradle file located at `ViroSample/android/build.gradle`. You'll see an `allprojects { ...}` block in the file as
```
allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
```
Add the following line below the `jcenter()` line
```
maven { url 'https://maven.google.com' }
```
That should be the only change you'll need. 
For your first error (in the complete log of the run) -> "Exit status 11, EventEmitter.<anonymous> error" This seems to be a `react-native` error rather than a Viro error. If you search online, you should find a lot of posts where other React-Native devs have run into the same issue like
https://github.com/react-community/create-react-native-app/issues/382
https://github.com/react-community/create-react-native-app/issues/533

Can you run through installing React Native on your Windows machine again by following instructions here -> https://facebook.github.io/react-native/docs/getting-started.html ? Make sure you select "Building Projects with Native Code" and development OS: "Windows" before following through the guide

Regarding your second error (your screenshot from Android Studio), that too seems to be a React Native Android Studio error folks have run into 
https://github.com/react-community/react-native-maps/issues/1813
https://stackoverflow.com/questions/35674066/errorexecution-failed-for-task-appprocessdebugresources-java-io-ioexcept
Following solutions mentioned in these posts should help resolve this problem for you.

Good luck!
