### ISSUE TITLE
error building release build android studio 

### ISSUE THREAD

**Issue by JamesBotterill** [viromedia/viro#357]
I'm currently getting an error when attempting to run the ./gradlew assembleGvrRelease script through the terminal. 

The reason provided is as follows

* What went wrong:
Could not list contents of '/Users/studio/concept/UCLmoments/node_modules/fsevents/node_modules/.bin/node-pre-gyp'. Couldn't follow symbolic link.

Thanks, 

James

**Comment by manbod** [comment]
Hi @JamesBotterill ,
This potentially seems like a react-native, rather than a ViroReact issue. Found similar issues looking issues:
https://github.com/facebook/react-native/issues/11212
https://github.com/facebook/react-native/issues/14417
https://github.com/srs/gradle-node-plugin/issues/190

Can you try removing `node_modules` and re-installing them? At the root of the project, run
```
rm -rf node_modules ; npm install
```
If that doesn't resolve this, what are your contents of package.json?

Let us know.

Thanks

**Comment by JamesBotterill** [comment]
Great that resolved the issue thanks
