### ISSUE TITLE
App crashes on device when building arRelease (Samsung s8+)

### ISSUE THREAD

**Issue by JamesBotterill** [viromedia/viro#360]
Currently when I'm attempting to run an ar release build on the samsung s8+ it crashes on launch, If I switch to gvrRelease everthing works correctly.

**Comment by manbod** [comment]
Hi @JamesBotterill ,
Thanks for reaching out. We'll need a little more info from you to be able to take a look at why you are running into a crash at launch.
What android version is running on your samsing s8+? 
Does it have ARCore installed on the device? 
Does AR debug work on the same device? What version of react-viro are you using? 
Can you capture logs from the device when it crashes and share them with us?

Thanks,

**Comment by JamesBotterill** [comment]
Hi @manbod 

I'm running Android 8.0.0 on my device, Yes I have AR core installed on the device, Yes the AR debug build was working without issue and I'm using the latest ViroReact (2.8.1).

I'm away from my dev machine today but will get logs when I get back on it.

**Comment by manbod** [comment]
Hi @JamesBotterill ,
Following up to see if you have any crash logs for this. Testing on 2.8.1, android release builds should be working. We've seen sometimes building through Android Studio fails since react-native sometimes skips bundling js and assets. In such cases, building from terminal works (`./gradlew assembleGvrRelease`) or running just the bundling task on terminal (`./gradlew bundleGvrReleaseJsAndAssets`) followed by building release signed builds via Android Studio. In any case, taking a look at your crash logs should help.

Thanks,

**Comment by robertjuh** [comment]
when i try ./gradlew assembleGvrRelease i get:

:app:processGvrReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processGvrReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.926 secs

**Comment by robertjuh** [comment]
This is probably not an answer to your question but it could be helpful when testing a release version of your app **without the remote debugger**:


```
if (!__DEV__) {
    console.log = () => {};
}
```

or just

`console.log = () => {};`

This will disable your console.logs. My application still worked but it seemed to freeze a lot because i had many console.logs in the project.

The reason this happens is because when the remote debugger is on, the javascript will run in the browser, and if it is off, the javascript will run on the react native JS thread which seems to have troubles dealing with console logs.
