### ISSUE TITLE
Cannot connect to debugger

### ISSUE THREAD

**Issue by vuthanhtrung0504** [viromedia/viro#380]
I cannot connect with debugger in chrome. It return error  message is connection to  http://2b38dd2a.ngrok.io:8081/debugger-proxy?role=client timed out

**Comment by manbod** [comment]
Hi @vuthanhtrung0504 ,
Thanks for reaching out. We'll need a little more info from you to be able to dig deeper into your issue. Please provide the following details: 
1. Are you seeing this error on iOS or Android? 
2. If iOS, on simulator or a physical device? 
3. What version of react-viro is your app using? 
4. What version of react native is your app using? 

I just tested this on the latest version of ViroReact (v2.9.0) and it seems to work on Android consistently, but fails intermittently on iOS. The intermittent iOS connection time out seems to be a known react-native issue on iOS. You can see same error seeing by other RN devs : 
https://github.com/facebook/react-native/issues/7685
https://github.com/facebook/react-native/issues/14186
https://stackoverflow.com/questions/37370916/react-native-error-connection-to-http-localhost8081-debugger-proxyrole-clie/43285071#43285071

Let us know if following solutions mentioned in this forums doesnt resolve the problem for you.

Thanks.

**Comment by vuthanhtrung0504** [comment]
I use  "react": "16.3.1", "react-native": "0.55.1", "react-viro": "2.9.0". I use IOS in the physical device. I'm not test in android yet. I try to refresh it many times but it still not work. My iphone and mac is connected with the same wifi and  this wifi is completely work fine. I also try http://2b38dd2a.ngrok.io:8081/debugger-ui/ but seem like it cannot open

**Comment by vuthanhtrung0504** [comment]
I found that it only happen when i turn debug remote JS on Viro media. When i build a debug version, the error is gone

**Comment by sjt145** [comment]
hello @vuthanhtrung0504  i had same problem...i solved it by following the steps here as it does not debug on chrome browser:

https://basecamp.kony.com/s/question/0D56A00000AnrmmSAB/how-to-debug-the-js-files-for-ios-using-safari-when-app-launched-in-simulator-or-in-device-connected-to-xcode

build your app first  from whatever source you building and enable WEB Inspector option in our device by following steps:
--> First go to Device settings

--> Then select safari option by scrolling down

--> Then select Advance settings which is at the bottom scroll screen completely.

--> Then select or On WebInspector 

In order to get Simulator appearing in Develop option at safari:
1)Open Safari -> Go to Preferences 
2)Then Click on Advanced tab.
3)Try to Uncheck and check "Show developer menu in menu bar".
4)Then Quit Safari and try to Relaunch
5)Now try to run your app when app starts running on emulator, open the Safari browser on your MAC
6)Developer menu will give you the emulator name in the list
7)Select your emulator and select JSContent
8)JSContent window will give you your application JS file.

and you will see you console.log outputs on safari windows when you run your app...
and here now you donot have to select debug remote JS as it will directly open window once you run ur app..
hope it helps you as it helped me..

**Comment by manbod** [comment]
Hi @vuthanhtrung0504 ,
Good to hear it works for you by building the debug version of the app. For debugging via the Viro Media app (Testbed), enter your mac's IP address (get it from Network preferences on your mac or by running `ifconfig en0`), instead of the ngrok address you read from the npm packager. Enter your IP address just as X.X.X.X, without the :8081 port . That should fix it. Let us know if entering IP address in the testbed app doesn't work for you.

Thanks,

**Comment by vuthanhtrung0504** [comment]
It's work with IP address without the port in testbed app.

Thanks
