### ISSUE TITLE
Application of post processing effect

### ISSUE THREAD

**Issue by Hudsons8** [viromedia/viro#381]
Hi,
I was wondering if it's possible to only apply ViroARScene post process effects to the camera feed but exclude viro objects/images rendered from the effects

**Comment by dthian** [comment]
Hey @Hudsons8, unfortunately we do not currently support an additional secondary post process effect that is only applied to the camera feed (since usually post processing is done when the whole scene is rendered). Could you explain a bit more what you are planning to build and trying to accomplish? Thanks!

**Comment by Hudsons8** [comment]
ah ok no worries, trying to build a retro style grayscale scene but with modern assets with colour, thanks.
