### ISSUE TITLE
Unable to use ViroARPlane or ViroARPlaneSelector

### ISSUE THREAD

**Issue by alexborton** [viromedia/viro#389]
## Environment
1. OS: Mac
2. Platform: iOS
3. Version: ViroReact: 2.9.1 and React Native 0.55.3
4. Device(s): iPhone 6s

## Description
I am unable to run either ViroARPlane or ViroARPlaneSelector. Both seem to simply do nothing. I am trying to anchor my object in the virtual space, but to no avail. The object works on it's own, but always appears behind me and does not want to scale or change position. 

## Reproducible Demo
This is the basics of the code i am running;

```
    <ViroARScene onTrackingUpdated={this.onInitialized} >
      <ViroAmbientLight color="#FFFFFF" />
      <ViroARPlane minHeight={0.5} minWidth={0.5} >
        <Viro3DObject
          source={testObj}
          type="OBJ"
          position={[0, 0.25, 0]}
          scale={[0.5, 0.5, 0.5]}
        />
      </ViroARPlane>
    </ViroARScene>
```

Also does not work;

```
    <ViroARScene onTrackingUpdated={this.onInitialized} >
      <ViroAmbientLight color="#FFFFFF" />
      <ViroARPlaneSelector minHeight={0.5} minWidth={0.5} >
        <Viro3DObject
          source={testObj}
          type="OBJ"
          position={[0, 0.25, 0]}
          scale={[0.5, 0.5, 0.5]}
        />
      </ViroARPlaneSelector>
    </ViroARScene>
```

I don't seem to get any errors or indication of anything going wrong. Note: testObj is an import of a .obj (quite large - around 10mb).

In the examples (GIF's) i see the plane for selection by the user - nothing like this appears for me in my camera view.

**Comment by alexborton** [comment]
It's also probably worth noting that i am using the static library setup. I also am unable to update the `ENABLE_BITCODE` setting to `yes` as this throws a linking error in that static library. This could have something to do with the planes - I'm not sure.

**Comment by manbod** [comment]
Hey @alexborton ,
Thanks for reaching out. I just verified by testing `ViroARPlane` and `ViroARPlaneSelector` on a iPhone 6s+ with ViroReact `2.9.1`. Can confirm both components are working as intended. Bear in mind, ARKit can sometimes take a little longer to detect planes in your surroundings. It mostly depends on lighting and other environmental factors. The plane for selection that you see in the examples GIF, you should see that before you tap on a plane when using `ViroARPlaneSelector`. You should see a greyish plane detected, which upon tapping should place the 3D Object. If you don't see one, perhaps try a different surrounding quickly to test?

Best way to confirm (and also help while debugging) that ARKit is actually finding a plane is to include a `ViroQuad` along with the `Viro3DObject` to be placed on the plane found by ARKit. That should help you determine where the plane was detected, and where the object is in relation to the plane. Try the following code snippet to test it out, replace the 3DObject with your testObj:
```
render() {
    return (
      <ViroARScene onTrackingUpdated={this._onInitialized} >
        <ViroAmbientLight color="#ffffff" />
        <ViroARPlane minHeight={.5} minWidth={.5}>
        <ViroQuad
          rotation={[-90, 0, 0]}
          scale={[.5,.5,1]}
          materials={"green_plane"}/>
        <Viro3DObject position={[0,0.1,0]}
          scale={[.2,.2,.2]} 
          type="VRX" source={require('./res/emoji_kiss_anim/emoji_kiss_anim.vrx')} 
          animation={{name:"02", delay:0, loop:true, run:true}}
          dragType="FixedToWorld" onDrag={()=>{}} 
          resources={[require('./res/emoji_kiss_anim/emoji_kiss_diffuse.png'), 
                      require('./res/emoji_kiss_anim/emoji_kiss_normal.png'), 
                      require('./res/emoji_kiss_anim/emoji_kiss_specular.png')]} />
        </ViroARPlane>
      </ViroARScene>
    );
  }
```
And include the following material to color the above quad green
```
ViroMaterials.createMaterials({
    green_plane: {
      lightingModel: "Constant",
      diffuseColor: "#00ff0050"
  },
});
```

For dragging, you'll notice I added `dragType="FixedToWorld" onDrag={()=>{}} ` to the 3D Object. For list of dragTypes -> https://docs.viromedia.com/docs/viro3dobject

For pinching, you'll need to implement the `onPinch` callback on the object. We recently open sourced our Figment AR App. Checkout how to quickly implement the onPinch callback here -> https://github.com/viromedia/figment-ar/blob/master/js/component/ModelItemRender.js#L221-L241. And if you havent already, checkout the app here -> https://itunes.apple.com/us/app/figment-ar/id1270018902?mt=8

ViroReact is built with `enable_bitcode` set to `NO` since GVR IOS SDK is built without bitcode. That's why unfortunately, us not including bitcode is just an artifact of one of our dependencies not including bitcode. 

Good luck!

**Comment by alexborton** [comment]
@manbod Thanks for getting back to me. I have since learned the phone is actually an iPhone 7 - but i'm not sure that will make a great deal of difference.

I tried the snippet you suggested and took and longer stroll around the office, but no luck... the camera is working, but nothing at all displays. I have a couple of screenshots of what should be very clear planes and yet nothing displays.

![image uploaded from ios](https://user-images.githubusercontent.com/1439507/44260695-2727e280-a20d-11e8-9815-4384c80fa52d.jpg)
![image uploaded from ios 1](https://user-images.githubusercontent.com/1439507/44260696-2727e280-a20d-11e8-928f-ea44bea209ef.jpg)

I used (almost) your exact code and left out my custom object for now;

```
/* eslint-disable */

import React, { Component } from 'react'
import { StyleSheet } from 'react-native'
import {
  ViroARScene,
  ViroConstants,
  Viro3DObject,
  ViroARPlane,
  ViroARPlaneSelector,
  ViroBox,
  ViroAmbientLight,
  ViroNode,
  ViroMaterials,
  ViroQuad
} from 'react-viro'

import testObj from './test.obj'

class HelloWorldSceneAR extends Component {

  constructor() {
    super()

    this.state = {
      text: 'Initializing AR...'
    }

    this.onInitialized = this.onInitialized.bind(this)
  }

  onInitialized(state, reason) {
    console.warn('onInit')
    if (state === ViroConstants.TRACKING_NORMAL) {
      this.setState({
        text: 'Hello'
      })
    } else if (state === ViroConstants.TRACKING_NONE) {
      // Handle loss of tracking
    }
  }

  render = () => {
    ViroMaterials.createMaterials({
        green_plane: {
          lightingModel: "Constant",
          diffuseColor: "#00ff0050"
      },
    });
    return (
      <ViroARScene onTrackingUpdated={this.onInitialized} >
        <ViroAmbientLight color="#ffffff" />
        <ViroARPlane minHeight={.5} minWidth={.5}>
        <ViroQuad
          rotation={[-90, 0, 0]}
          scale={[.5,.5,1]}
          materials={"green_plane"}/>
        <Viro3DObject position={[0,0.1,0]}
          scale={[.2,.2,.2]}
          type="VRX" source={require('./res/emoji_kiss.vrx')}
          animation={{name:"02", delay:0, loop:true, run:true}}
          dragType="FixedToWorld" onDrag={()=>{}}
          resources={[require('./res/emoji_kiss_diffuse.png'),
                      require('./res/emoji_kiss_normal.png'),
                      require('./res/emoji_kiss_specular.png')]} />
        </ViroARPlane>
      </ViroARScene>
    )
  }
}

export default HelloWorldSceneAR
```

**Comment by alexborton** [comment]
I am not sure how this slipped under the radar, but the 7 i was testing on only have 10.3 OS... so that's more than likely the cause there?

I tested on a 6+ with 11.4 and it worked as expected!

**Comment by dam00n** [comment]
Yep, ARKit requires min iOS 11. Glad you got it working.

**Comment by faizan1990** [comment]
Hi @alexborton, In you `<Viro3DObject>` you have defined `source` as `{testObj}`. Can you please tell me how you have defined `testObj` in your code? Is it a plain array of files required or is it in the same syntax as we use to `require` a single file in `Viro3DObject`?

**Comment by HassanAfnan** [comment]
hey! I want to place a points on mobile touch tab on ViroPlane to get the distance between one point to other, I have done everything I just to know how can place multiple objects on a plane. anyone know?
