### ISSUE TITLE
Multiple image marker UI learning?

### ISSUE THREAD

**Issue by Geli25** [viromedia/viro#423]
Hi guys,

I am still quite new to ViroMedia and I am just wondering if there is a way to use multiple markers as one marker for better accuracy in determining the location of the 3D object? Right now all examples I see in the documentation is that one marker supports one object. Ar.js has a learning UI for multiple markers, is this not supported by ViroMedia at the moment?

Thanks for your help!

**Comment by achuvm** [comment]
Hi @Geli25,

From what I understand, AR.js does not actually contain a SLAM engine and relies exclusively on marker based localization which is inherently unstable because tracking is lost when markers are not visible. Our system is built upon ARKit and ARCore which enables the developer to place and use objects without the use of markers (ie. You can place a box at [0,0,-1], and it will be placed 1 meters in front of when the user enters the experience without the use of any markers). In short, our `ViroARImageMarker`s are used to simply find image targets vs used to establish the location of the user, we rely on the underlying SLAM engine for localization instead.

Let us know if you have any other questions! 

Thanks for trying out Viro,

**Comment by Geli25** [comment]
Thank you so much for your input. I thought the image recognition on Viro was similar to AR.js where it doesn't need ARCore to run, but this makes sense, thank you!

If it's ok for me to ask another question on this thread, ARkit is also beginning to support object recognition via 360 scanning, are you going to support that in ViroMedia as well? Right now it is possible to do it as a separate thing in ARKit, but I am not sure how to do that with ViroReact.

**Comment by achuvm** [comment]
Hi @Geli25,

Glad I could help.

We already support the Object Detection in ARKit 2.0 (with iOS 12) through the `ViroARObjectMarker` component here: https://docs.viromedia.com/docs/viroarobjectmarker. Try it out and let us know if it doesn't work for you!

Thanks,

**Comment by Geli25** [comment]
Oh I didn't realize! I will try that out, thank you so much! :)

**Comment by manbod** [comment]
Closing this issue. Let us know if you have more question. :)
