### ISSUE TITLE
Invarint Violation: Element type is Invalid

### ISSUE THREAD

**Issue by u-can-miracle** [viromedia/viro#446]
- [x] Review the documentation: https://docs.viromedia.com/
  - [x] Search for existing issues: https://github.com/viromedia/viro
  - [x] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Environment
Please provide the following information about your environment:
1. Development OS: Linux 18.04
2. Device OS & Version: Android OS version 8.0?
3. Version: ViroReact version and React Native version:
```
    "react-native": "0.55.1",
    "react-viro": "2.11.0",
```
and global packages
```
"react-native-cli": "2.0.1",
"react-viro-cli": "2.11.0"
```

4. Device(s): Google Pixel 2

## Description
When I connect with my device to testbed I see error: 'Invarint Violation: Element type is Invalid ...'
![screenshot_20181027-185151](https://user-images.githubusercontent.com/16516865/47606250-e83ab800-da19-11e8-9d29-63cf8ce0fc4c.png)

## Reproducible Demo
just start my [test-app](https://github.com/u-can-miracle/viro-ar) with `npm start`

**Comment by manbod** [comment]
Hi @u-can-miracle ,
This is mostly a bug in the way you are importing / exporting some component, rather than it being a bug with Viro. You can look at these react-native issues below for hints on identifying where you might be doing something wrong:
https://github.com/facebook/react-native/issues/16332
https://github.com/react-navigation/react-navigation/issues/2767
https://github.com/facebook/react-native/issues/20397

Hope this helps.

Thanks,

**Comment by u-can-miracle** [comment]
There are no one solution
