### ISSUE TITLE
PBR not working on IOS after compiling app to binaries

### ISSUE THREAD

**Issue by Tino-F** [viromedia/viro#452]
- [X] Review the documentation: https://docs.viromedia.com/
  - [X] Search for existing issues: https://github.com/viromedia/viro
  - [x] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Environment
Please provide the following information about your environment:
1. Development OS: 
Mac
2. Device OS & Version: 
IOS 12
3. Version: ViroReact version and React Native version 
Viro React 2.11.0
React Native 0.55.1
4. Device(s): What device(s) are you are seeing the issue on (i.e. iPhone X, Samsung Note 8, etc)
IPhone 6S
## Description
When I run the development app in XCode, PBR works fine and I get a shiny texture on my model, but after archiving the app and uploading it to TestFlight, the PBR goes away and the model has a matte texture on it. 

## Reproducible Demo
```

<ViroARSceneNavigator
            apiKey='xxxxxxxxxxxxx'
            initialScene={{scene: myScene}}
            style={{flex: 1}}
            debug={true}
            hdrEnabled={true}
            pbrEnabled={true}
          />

...

ViroMaterials.createMaterials({
  rocks: {
    lightingModel: 'PBR'
  }
})

...

<ViroDirectionalLight position={[0, 0.5, 0]} color="#ffffff" direction={[0, -.01, 0]} attenuationStartDistance={10} attenuationEndDistance={20} castsShadow={true} shadowMapSize={2048} shadowNearZ={2} shadowFarZ={5} shadowOpacity={.7} intensity={500}/>
<ViroAmbientLight color="#ffffff" intensity={1000}/>
<ViroOmniLight
  intensity={13000}
  position={[0, 0.3, 0]}
  color={"#fff8c2"}
  attenuationStartDistance={20}
  attenuationEndDistance={30}
  />

<ViroSpotLight
  color="#ffffff"
  attenuationStartDistance={5}
  attenuationEndDistance={10}
  position={[0, 0, 0]}
  direction={[0, -1, 0]}
  innerAngle={0}
  outerAngle={35}
  intensity={12000}
  />

<Viro3DObject source={require('../assets/models/rockstorm9.vrx')}
    position={[-0.03, -1.8, 0.0]}
    scale={[0.0011, 0.0011, 0.0011]}
    materials={['rocks']}
    type="VRX"
    animation={{name:'OSG_Scene', run: true, loop: true}}/>
```

**Comment by TCPILOT** [comment]
I'm having the exact same issue here. Same versions...

**Comment by Tino-F** [comment]
It only happens when I run the release build/archive the app

**Comment by achuvm** [comment]
Hi @Tino-F,

I took a look at your code and there are 2 issues:

1) the `materials={['rocks']}` property is unnecessary for FBX models as the lighting model is specified within the FBX object format.

2) this is working in debug but not release/archive because of how React Native works. When you converted your `.fbx` to `.vrx` it spit out a few other png/jpg that the file uses as textures. In debug mode w/ a package server, you didn't need to `require()` them because they're treated as url files. However, to make them available in release, you need to `require()` the files in order for React Native to know that it needs to bundle the assets. This is where the `resources=[]` property comes in handy.

So to get your object working, it should look something like this:

```
            <Viro3DObject
              source={require('./res/wheels.vrx')}
              type='VRX'
              resources={[
                require('./res/wheels_Base_Color.jpg'),
                require('./res/wheels_Metallic.jpg'),
                require('./res/wheels_Roughness.jpg'),
                require('./res/wheels_Normal_OpenGL.jpg'),
              ]}/>
```

**Comment by Tino-F** [comment]
Requiring the textures resolved the issue. Thank you!
