### ISSUE TITLE
[Feature Request] - Assets caching and loading on demand

### ISSUE THREAD

**Issue by vnovick** [viromedia/viro#476]
- [X] Review the documentation: https://docs.viromedia.com/
  - [X] Search for existing issues: https://github.com/viromedia/viro
  - [X] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Description
It's crucial that there should be some caching mechanism for assets on application start for faster loading times and for assets reuse.

Also It will be great to have some kind of bundling for assets to load them on demand. Something like AssetBundles in Unity

**Comment by achuvm** [comment]
Hey Vlad,

This is a limitation of React Native itself.

If you'd like to "bundle" assets, you can either build in release, or include them in the iOS/Android projects. Then when you refer to them in React Native, simply pass in the filepath to the files on disk using `{ uri : file://path/to/file }` rather than a `require()`. 

Something that might help with the slow loading times is to use your local IP address (rather than the ngrok address) or, if you have an Android device, you can consider attaching the device to your computer using USB and reverse tether with `adb reverse tcp:8081 tcp:8081`.

You can also see if there are 3rd party React-Native libraries that help with this bundling issue too.
