### ISSUE TITLE
Get Viro3DObject screen coordinates

### ISSUE THREAD

**Issue by ibesora** [viromedia/viro#539]
Is it possible to get the screen coordinates of a rendered Viro3DObject? 
I want to add a react component on the pixel position of the object as a label. 
Something like what [PeakFinder ](https://itunes.apple.com/us/app/peakfinder-ar/id357421934?mt=8) does.

**Comment by manbod** [comment]
Hi @ibesora ,
Thanks for reaching out. Yes, if you know the [x,y,z] coordinates of the Viro3DObject, you should be able to use `async project(point:array)` function in `ViroARSceneNavigator` to get screen 2D coordinates. Docs [here](https://docs.viromedia.com/docs/viroarscenenavigator). 

Let us know if you run into issues there.

Thanks

**Comment by ibesora** [comment]
Hi @manbod , 
I'm using the project method as you said (sorry about that, I was looking at the ViroARScene methods, not ViroARSceneNavigator one) but I keep getting this error when using project: 
![screenshot_20190212-105853_fitesilimits](https://user-images.githubusercontent.com/2301378/52627460-ad1fa000-2eb5-11e9-9334-4dff2aa0b3d6.jpg)

I'm using this code:
```
this.props.arSceneNavigator.project([-1, 4, -5]).then((returnPos)=> {
    console.log(returnPos)
}, (err) => console.log(err));
```

It seems to be a problem with the native part of Viro, doesn't it?

**Comment by manbod** [comment]
Hey @ibesora ,
I just tested the project method on our end in v2.13.0 and it seems to be working correctly. Copy pasting the HelloWorldSceneAR.js that works. We'll need a little more info to help you here.

1. What version of react-viro version are you using? 
2. Do you see this error in a standalone app built with react-viro or in the Viro Media testbed app?
3. If standalone app, did you run the `setup-ide.sh --android` script?
3. When you see this red screen, can you look into Android logs and see (and share with us) if you can find a NullPointerException in java logs? An exception trace there would be very helpful.

Very likely this nullpointer exception is due to something else in your scene. Following Scene works correctly. Have a look
```js
'use strict';

import React, { Component } from 'react';

import {StyleSheet} from 'react-native';

import {
  ViroARScene,
  ViroText,
  ViroConstants,
} from 'react-viro';

var projectPoint = [1, 1, -4];
export default class HelloWorldSceneAR extends Component {

  constructor() {
    super();

    // Set initial state here
    this.state = {
      text : "Initializing AR..."
    };

    // bind 'this' to functions
    this._onInitialized = this._onInitialized.bind(this);
    this._projectPoint = this._projectPoint.bind(this);
  }

  render() {
    return (
      <ViroARScene onTrackingUpdated={this._onInitialized} >
        <ViroText text={this.state.text} onClick={this._projectPoint} scale={[.5, .5, .5]} position={[0, 0, -1]} style={styles.helloWorldTextStyle} />
      </ViroARScene>
    );
  }

  _projectPoint() {
    this.props.arSceneNavigator.project(projectPoint).then((rectDict)=> {
        console.log(rectDict);  
    }, (err) => console.log(err));
  }

  _onInitialized(state, reason) {
    if (state == ViroConstants.TRACKING_NORMAL) {
      this.setState({
        text : "Hello World!"
      });
    } else if (state == ViroConstants.TRACKING_NONE) {
      // Handle loss of tracking
    }
  }
}

var styles = StyleSheet.create({
  helloWorldTextStyle: {
    fontFamily: 'Arial',
    fontSize: 30,
    color: '#ffffff',
    textAlignVertical: 'center',
    textAlign: 'center',  
  },
});

module.exports = HelloWorldSceneAR;

```

**Comment by ibesora** [comment]
Hi again @manbod and thanks for your help.
I am on viro 2.13 building a standalone app.
Looking at Android logs, the only thing I can see is the exception reported by React Native on the screen capture I posted earlier.
Running your scene on my project worked perfectly and then I noticed that you defined a onTrackingUpdated function. If I enable the click handler only when the tracking state is ViroConstants.TRACKING_NORMAL it goes perfectly on my own scene so it seems there might be some kind of problem if the ViroARScene is not yet initialized. 
Running your scene with this modified render method on the example app reproduces my problem
```javascript
render() {
    return (
      { this._projectPoint() }
      <ViroARScene onTrackingUpdated={this._onInitialized} >
        <ViroText text={this.state.text} onClick={this._projectPoint} scale={[.5, .5, .5]} position={[0, 0, -1]} style={styles.helloWorldTextStyle} />
      </ViroARScene>
    );
  }
```

**Comment by manbod** [comment]
Ah, makes sense. We should probably update our docs to call that out. That it is by design. You want the tracking to be normal / initialized for the ViroARScene's coordinate system to be initialized (as to where the x,y,z axis are pointed)-> for the project/unproject to work correctly. We call that out to some effect here -> https://docs.viromedia.com/docs/ar-tracking-and-anchors

In any case, doing otherwise shouldnt result in the red screen which points to a NullPointerException in our platform. We've logged in a bug internally and should fix in an upcoming release. But your code shouldn't be affect by the fix.

Thanks for catching this. Apologies for the inconvenience.

**Comment by ibesora** [comment]
Don't worry! And thanks for your work. Viro is such a nice platform to work with.

**Comment by skizzo** [comment]
Is it possible to do that the other way round? Meaning, translating screen coordinates to Viro Scene coordinates? Would be really handy to implement a "touch to position" feature. Thanks!

**Comment by wherear** [comment]
> Is it possible to do that the other way round? Meaning, translating screen coordinates to Viro Scene coordinates? Would be really handy to implement a "touch to position" feature. Thanks!

there is a method called 'unproject', i would venture that it is exactly what you are looking for:

> async unproject(point:array)
> function called that takes a 3d vector representing a 2d screen position plus a value from 0 to 1 representing a interpolation from the near clipping plane and far clipping plane, and returns a vector representing a x,y,z world space position of the given screen position.

https://viro-community.readme.io/docs/viroarscenenavigator#async-unprojectpointarray
