### ISSUE TITLE
ViroSpotLight shadows inverted with portals

### ISSUE THREAD

**Issue by ChristianNormann** [viromedia/viro#549]
## Environment
1. Development OS: macOS Mojave, 
2. Device OS & Version: Various devices, e.g. iOS 11.4 and Android 9
3. Version: ViroReact version 2.13.0 and React Native version 0.57.7
4. Device(s): Various devices, e.g.: iPad Pro 12.9, OnePlus 6

## Issue
I have used a portal to create a hole in the ground. Inside the portal is the hole (grey concrete), as well as the content of the hole as 3D objects (pipes, wooden bars, etc.). When I place a ViroSpotLight above the hole and light down on the content in the hole, I would expect the bottom of the hole to be lit up, and see the shadows from the pipes. Instead the bottom of the hole is covered in a big shadow. The border of the bottom of the hole, however, is lit up, which is the opposite of what I would expect. The behaviour is the same whether I put the ViroSpotLight inside the portal, or outside the portal.

![withportal](https://user-images.githubusercontent.com/6575372/52859811-00038c80-312e-11e9-8909-69280fb9c977.png)

If I remove the portal, but keep everything else as it is, then the shadows look right (notice the shadows of the pipes):
![withoutportal](https://user-images.githubusercontent.com/6575372/52859941-64bee700-312e-11e9-9085-efeca7345433.png)

**Comment by dam00n** [comment]
Hi @ChristianNormann, very cool use of portals. Regarding your issue, it looks like the portal itself is being case as a shadow. I am not able to repro this because I am not sure what variable you are using. But some possible work arounds...

1. If you have an ARShadowReceiver on your ViroPortal 3D Object Frame, try removing it.
2. Move the Spotlight closer to the portal so that it is not casing against the portal frame
3. Play around with the values for innerangle, outerangle, shadownearz and shadowfarz
4. Reduce the size of your ViroQuad

If you are still having issues, can you share code so we can repro on our end?

**Comment by ChristianNormann** [comment]
Hi @dam00n, thanks for the reply. It was indeed the object used as a portal, that casted a shadow. The fix was to set shadowCastingBitMask=0 for the portal 3D object.
