### ISSUE TITLE
Building Native App

### ISSUE THREAD

**Issue by Zirconiumirish** [viromedia/viro#55]
Hello, I was wondering if you could help me for the building part (Final App)

I'm trying to build the app with android studio and launching the app but it seem to be linked again with the localhost server . And show a red screen with error to communicate with server

Could we build the app with everything integrated in the app (Scene, Images) ?

Thanks for your help

Michael

**Comment by achuvm** [comment]
Hi @Zirconiumirish,

Assuming you've already run our `./setup-ide.sh` script for Android, we share the same release build instructions as React-Native, which can be found here:

http://facebook.github.io/react-native/releases/0.47/docs/signed-apk-android.html

If you wanted to build release through Android Studio instead, you would still need to run `./gradlew bundleGvrReleaseJsAndAssets` or `./gradlew bundleOvrReleaseJsAndAssets` depending on which build you want because that's how React-Native bundles the assets you use in JS.

Let us know if you run into any trouble with that!

- Andy

**Comment by Zirconiumirish** [comment]
Alright Thanks =)
