### ISSUE TITLE
Cannot show 3D object

### ISSUE THREAD

**Issue by vivikenen** [viromedia/viro#73]
I followed the document to set up the project and try to use 3D object for AR.
It can show text and ViroBox, but not 3D object, even I use the same 3D model and code from the ARSample.

Just wondering which part I did wrong?

<img width="1033" alt="screen shot 2017-10-30 at 12 36 47 pm" src="https://user-images.githubusercontent.com/11569400/32151208-186f10ac-bd6f-11e7-9ca4-5b69059f2875.png">

**Comment by VikAdvani** [comment]
Hi @vivikenen, 

There are two possible issues from looking at the code:
1)There's no lighting in the scene, so the model doesn't appear properly.
2)The object is scaled too small and positioned too far so it won't render. 

**Solution to to the lighting issue:**
3d Objects tend to define their own lighting model so a light will likely needed to be added to the scene for the object to appear. Try adding an ambient light to the scene like below:

```
  <ViroAmbientLight color="#ffffff" intensity={500}/>
```

See if you can see the object after adding the light. If it's too dark, try increasing the intensity or adding another light like a directional or spot light. Check out our lighting guide here: http://docs.viromedia.com/docs/3d-scene-lighting for more info.

**Solution to scale issue:**
In addition you might want to increase the scale from .1 to .5 and position the object closer(make the z -5 instead of -10). If the object shows up then it was scaled too small to begin with.

If that doesn't work let us know!

**Comment by vivikenen** [comment]
@VikAdvani  thx for your kind help, it works now
