### ISSUE TITLE
Intersecting Viro Images - Clipping depending on renderingOrder

### ISSUE THREAD

**Issue by k4r1** [viromedia/viro#762]
## Checklist:
  - [x] Review the documentation: https://docs.viromedia.com/
    - The only thing I found that might be related is `renderingOrder`, but I could not resolve the issue with this
  - [x] Search for existing issues: https://github.com/viromedia/viro
    - Maybe related to https://github.com/viromedia/viro/issues/746
  -  [x] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases
    - Using 2.17.0

## Environment
1. Development OS: Mac
2. Device OS & Version: iPhone XS - iOS 13.1.2
3. Version: 
   - ViroReact: 2.17.0
   - React Native: 0.61.2
4. Device(s):
   - iPhone XS

## Description
Rendering two ViroImage (or ViroAnimatedImage) components that intersect causes one of the images to be cropped at the point of intersection, depending on the rendering order.

## Reproducible Demo
The code below takes a PNG with the outline of a circle and renders it twice such that the two planes intersect at 90 degrees.

```
    <ViroARScene>
      <ViroNode position={[0,0,-1]}>
        <ViroImage height={0.5} width={0.5} source={require('./res/debug-circle3.png')} rotation={[-45,-45,-45]} />
        <ViroImage height={0.5} width={0.5} source={require('./res/debug-circle3.png')} rotation={[45,45,45]} />
      </ViroNode>
    </ViroARScene>
```

Depending on the order that you have the nodes (or the `renderingOrder` you set on the `ViroImage`s), one of the circles will be "clipped" by the other and only render half.

**Expected Behaviour:** Both circles should be rendered fully.
![image](https://user-images.githubusercontent.com/16408267/67156355-f29f4180-f34f-11e9-8323-8df6f5a843bf.png)

**Comment by k4r1** [comment]
Hi @dthian, if possible could you give me some pointers on how I might begin debugging this? I'm happy to contribute a fix upstream if I can figure this out, but as it stands I'm unsure where to start.

**Comment by k4r1** [comment]
Upon further investigation it seems like this issue is also present in https://github.com/viromedia/virocore/ and so is not specific to react-viro.

**Comment by dthian** [comment]
Hey @k4r1, you can toggle the readsFromDepthBuffer boolean in ViroMaterial as seen here: https://docs.viromedia.com/docs/materials. You might be able to just define a material with no depthReads and set it on the ViroImage. But i'm not sure if ViroImage would just override your settings. 

If setting the material on a ViroImage doesn't work, you could also try using a ViroQuad with the desired material.

**Comment by k4r1** [comment]
Nice, thank you for the suggested workarounds. I'll give those a try.

In the mean time, do you think this is the behaviour that we want by default from a ViroImage? Would it be better for me to open a PR to set `readsFromDepthBuffer` to `false` by default on a ViroImage (or expose a prop in React that can toggle that?)

**Comment by k4r1** [comment]
So I tried switching off reading from the depth buffer, and although this now solves the clipping issue, the images no longer intersect at all.

![IMG_1599](https://user-images.githubusercontent.com/16408267/67639214-194d1180-f928-11e9-807e-ee2b9fe40124.png)

The expected behaviour is for one of the images to obscure the other, but only the opaque parts

**Comment by dthian** [comment]
> In the mean time, do you think this is the behaviour that we want by default from a ViroImage? 

Not exactly, there can be situations where the user would want ViroImages to be occlude or be occluded by other 3D objects - the depth buffer check would be important for these cases. 

> The expected behaviour is for one of the images to obscure the other, but only the opaque parts.

I'm not sure if i understand here - aren't both the image's black outline and solid white middle opaque?

**Comment by k4r1** [comment]
Yes, and so you would expect one image to cut through the other, like in the third image above. With the depth checking switched off, you simply get one image fully on top of the other, line in the middle example above.

I think that we need to have the depth checking turned on, but the issue is that transparent pixels are able to occlude opaque ones. Does that make sense?

**Comment by dthian** [comment]
> but the issue is that transparent pixels are able to occlude opaque ones. 

Not really, the issue is that you are drawing a quad that is closer to the camera, before drawing another quad that is further. Therefore the closer quad will 'cover up' whatever was draw on the underlying further quad because of depth. It so happens that in this case, your quad has a transparent portion. However, depth checking is independent of 'transparency blending'. 

Currently, Viro enables the setting of transparency on materials. This in turn tells the renderer to prioritize rendering transparent / semi-transparent items last. For example, if you render a semi-transparent "window" last, it is visually correct as opaque objects behind the window is rendered first.

However, since you have two objects that are both semi-transparent and are basically in the same positional location in world space, the above solution doesn't work. In this case you will need to define the render order (with depth writing or reading disabled), so as to get the desired visual output you like.

> Yes, and so you would expect one image to cut through the other, like in the third image above. With the depth checking switched off, you simply get one image fully on top of the other, line in the middle example above.

Oh right my bad, i thought the 3rd image was what you were seeing in Viro. If you render the vertical circle first, and then the horizontal circle  - that should work?

**Comment by k4r1** [comment]
> ...drawing a quad that is closer to the camera, before drawing another quad that is further...

Actually, the average distance from the camera to each quad is the same. Because of how they are placed, at some points, quad A is closer than quad B, and at other points it is the other way around.

> For example, if you render a semi-transparent "window" last, it is visually correct as opaque objects behind the window is rendered first.

I don't believe the rendering behaviour exhibited by default is correct actually, what is happening is that the transparent regions of the quad in the foreground are "punching a hole" through to the background, and thus planes which are (partially) behind said quad are occluded, even though they should be visible.

> If you render the vertical circle first, and then the horizontal circle - that should work?

This doesn't work - it just changes which plane is incorrectly occluded, per the original issue description.

> Because your desired 3d output has overlapping geometry meshes with transparent regions, instead of hacking it with two surfaces like the above, another way is to have a single 3D object mesh that represents your visual output. That way, this wouldn't incur issues with depth checks.

The example above is not a "hack", it is a minimum example to illustrate the bug around rendering two intersecting 2d planes. The application itself is much more complicated, but the underlying issue is with how intersecting planes with transparency are rendered.

---

Perhaps I can illustrate this bug a bit more clearly by changing the angle the planes are placed at:
![image](https://user-images.githubusercontent.com/16408267/68072222-38cbba80-fdbe-11e9-8da2-d35682883b72.png)

Especially in the image on the left, you can clearly see that when the vertical plane is closer to the camera, the transparent regions are occluding the horizontal plane, which is further away. Image on the right is included for completeness and shows what happens if you change the rendering order - it's harder to notice but the rendering bug is still present as the bottom half of the vertical circle is now missing.

**Comment by k4r1** [comment]
Did some further investigation on this - it seems this issue is only present when the planes actually intersect.

![image](https://user-images.githubusercontent.com/16408267/68072746-e1c8e400-fdc3-11e9-9c8d-c801472b85a1.png)

Here I'm rendering three planes; two that are the same distance away from the camera but at different angles (as in the original example) and one that is behind both of them.

You can see that the transparency between the two foreground planes and the background one is working as expected, but we're still getting the "punching a hole" behaviour with the two foreground planes.

**Comment by dthian** [comment]
> Actually, the average distance from the camera to each quad is the same. Because of how they are placed, at some points, quad A is closer than quad B, and at other points it is the other way around ... transparent regions of the quad in the foreground are "punching a hole" through to the background, and thus planes which are (partially) behind said quad are occluded, even though they should be visible.

So the ViroRenderer (and usually basic renderers), a node's *entire* geometry is rendered onto the screen (and thus its z location into the depth buffer), one at a time. As such, in your case, as mentioned above, one *entire* quad is rendered *before* the next quad is rendered. So if the first *entire* rendered quad is closer to the camera, its transparent regions will cover parts of the second one im the depth buffer *because the whole quad's geometry is rendered first, before the second quad (standard render behavior).* This effectively punches a hole into the background.

This can seen in your image:

![68072746-e1c8e400-fdc3-11e9-9c8d-c801472b85a1](https://user-images.githubusercontent.com/1904934/68074917-4b160c00-fd5e-11e9-8aed-c00dbba1b46b.png)

Where the verticle circle's transparent parts are closer to the screen and thus covering up part of the horizontal circle behind because its *entire quad* is drawn first.

Again, this is mainly because transparency  is currently independent of depth buffer updates, one doesnt affect the other.

I think this is standard rendering behavior. One thing you can try is to reproduce this in unity 3d and see what happens.

**Comment by k4r1** [comment]
Thanks very much for taking the detailed explanation about how this works within the rendering engine - it now makes sense to me why we're seeing this behaviour.

I downloaded Unity and gave this a try, you're right that by default it doesn't write to the depth buffer with the `Sprites/Default` shader. However if I create a material and attach it to the sprites, and then apply the `Standard` shader, I get the desired output:

![image](https://user-images.githubusercontent.com/16408267/68080115-71f04300-fe2f-11e9-9d23-735f35cc3675.png)

**Left:** Out-of-the-box behaviour, no Z writes
**Right:** Using Standard shader instead of the Sprite/Default one.

I'd really like to stick with Viro if possible though - is there a way to achieve the same behaviour with the existing APIs available within Viro? Or would this require changes to the underlying ViroRenderer?

**Comment by k4r1** [comment]
> However as first mentioned in this thread, if you disable the depth buffer read on the material with transparent areas, you would not get the "punching a hole into the background" issue. However, you will still have to define render order to achieve the final visual result u are expecting.

This produces the same output as the default shown in Unity - which still isn't quite right as it just renders one entirely on top of the other. Unless there's some extra step I'm missing here?

**Comment by dthian** [comment]
> I downloaded Unity and gave this a try, you're right that by default it doesn't write to the depth buffer with the Sprites/Default shader. However if I create a material and attach it to the sprites, and then apply the Standard shader, I get the desired output

Oh that is interesting, two quick questions: 

1) What's the difference between creating a "sprite square" object vs a 3D quad in Unity? Sprite squares seem to have a 2D notion.

2) What's the difference between the "Sprites/Default shader" and the "Standard shader"? Why does using a standard shader on a sprite square work?

**Comment by k4r1** [comment]
1. I'm not sure what the difference is, but I tried creating the same scene and was able to get it to correctly render with Quads if I use the "Unlit/Transparent Cutout" shader.

2. I dug into the shader definitions and the one for "Standard" seems to be quite complicated, as I assume its trying to account for lots of different cases.

Since the "Unlit/Transparent Cutout" shader seems like a more specific version of the thing we want, I think we can compare against that one instead of the whole standard shader.

The cutout shader is here:
https://github.com/TwoTailsGames/Unity-Built-in-Shaders/blob/bab22c6c04df30e674a47f225e946072c86222cb/DefaultResourcesExtra/Unlit/Unlit-AlphaTest.shader

The default sprites shader is here:
https://github.com/TwoTailsGames/Unity-Built-in-Shaders/blob/master/DefaultResourcesExtra/Sprites-Default.shader

I don't have a lot of knowledge in the domain so it's going to take me a while to unpick these, I'll update if/when I figure out how these might work. In the mean time, do you have any thoughts about what would be needed to enable this kind of rendering in Viro?

**Comment by dthian** [comment]
> The default sprites shader is here: TwoTailsGames/Unity-Built-in-Shaders:DefaultResourcesExtra/Sprites-Default.shader@master 

I'm not familiar with Unity shaders, but it does look like the default sprite shaders turn off any DepthWriting in the Z buffer [here](https://github.com/TwoTailsGames/Unity-Built-in-Shaders/blob/master/DefaultResourcesExtra/Sprites-Default.shader#L29). This makes sense and aligns with what we have discussed above.

> The cutout shader is here: TwoTailsGames/Unity-Built-in-Shaders:DefaultResourcesExtra/Unlit/Unlit-AlphaTest.shader@bab22c6

This shader looks like it is essentially using a **discarding method**, where rendered pixels with an alpha value that is less than a predefined **cutoff** is discarded, and **thus not rendered into the depth buffer**. As a result, the transparent parts of the circle aren't written into the depth buffer, and the transparency issues are mitigated.

However, **there is a performance hit** when this is done - which may be why Unity3D does not have this "Discarding/Cut-off" shader on as default (or AlphaTesting). This is also probably the case why we didn't have it implemented in Viro as well.

In a nutshell, in a render pass, when rendering a given pixel, early z-depth testing is done to prevent unnecessary executions of the Fragment Shader. A fragment/pixel is be discarded to save performance to avoid executing the fragment shader (due perhaps to being behind other geometry). There is specialized hardware that makes this particularly efficient in many GPUs. **However**, whenever fragments are discarded in shader code (or via GL_ALPHA_TEST or the Alpha-Cutoff methods as described above), it **disables early z-depth testing within the graphics pipeline, and thus this results in a performance hit.** 

> In the mean time, do you have any thoughts about what would be needed to enable this kind of rendering in Viro?

Hm, off the top of my head, I think it's definitely possible to achieve the above by adding a Fragment shader modifier to mimic the "Discarding/Cut-off" behaviour where fragments / pixels with an alpha value below a given threshold are discarded. This can be made toggle-able so that is not enabled by default. 

[ViroCore](https://github.com/viromedia/virocore) is currently open source right now, feel free to make the changes there and re-build the renderer / framework, or if you'd like modify this issue into a feature request for the community to pick up.
