### ISSUE TITLE
[Question] future of viroreact

### ISSUE THREAD

**Issue by vicpon** [viromedia/viro#853]
Hi, sorry if this is the wrong place to ask, but what is the future of this framework? It seems that many of the core developers/founders have moved on from ViroMedia. I think it's great that it was open sourced for the community to continue to use and develop it, but are any of the initial creators going to provide any support? Thanks

**Comment by visionari-labs** [comment]
My team is also curious about the future support for viro as we're looking to build cross platform AR/VR experiences with React Native.

**Comment by MinhazMM** [comment]
Is there any alternatives apart from Viro React when it comes to developing VR Apps?

**Comment by vicpon** [comment]
> 
> 
> Are there any alternatives apart from Viro React when it comes to developing VR Apps?

Yes, there are some free, some paid. A few: Unity (AR Foundation), Vuforia, Wikitude, ARKit, ARCore. It depends on what type of app you're building. If you're looking for a more direct replacement to ViroReact you can take a look at a-frame (or ar.js, which uses a-frame).

**Comment by MinhazMM** [comment]
Thank you @vicpon, but is a-frame for react native? Because I am developing a VR video app via React Native and then I stumbled upon the issue where Apple doesn't allow apps that contain UIWebView to be published to the store.

**Comment by vicpon** [comment]
@MinhazMM I'm not sure about that. I haven't published to app store in a while as I mostly do Android development and last iOS app I made was native. I haven't used it, but have you looked at this project? https://github.com/react-native-ar/react-native-arkit

**Comment by MinhazMM** [comment]
> @MinhazMM I'm not sure about that. I haven't published to app store in a while as I mostly do Android development and last iOS app I made was native. I haven't used it, but have you looked at this project? https://github.com/react-native-ar/react-native-arkit

@vicpon But this is for AR right? And not VR?

**Comment by vicpon** [comment]
@MinhazMM my bad. I just noticed you specifically said VR.

**Comment by MinhazMM** [comment]
> @MinhazMM my bad. I just noticed you specifically said VR.

So there aren't any RN alternatives for VR yeah?

**Comment by nazmifeeroz** [comment]
The author seems to avoid the question directly. i'm really concern about viro-react future. So far I couldn't find a better react native AR package as good as this...

**Comment by RoyceLeonD** [comment]
Hey Guys,I am not affiliated with Viro. But I would like to help recreate the community, and update the code. Can we start a discussion thread (Here) about all the features that need to be updated? I am willing to donate at least 5-6h a week to patch the core, and the mappings. 

Things to do Next 2 weeks:
1. Create a goal list of patches.
2. Create a small Community of Devs (me, hopefully 2-3 others, I can get some of my post-doc co-workers to help when they can)
3. Enable Projects, and Start migrating code into a test branch.

I could really use some help. @nazmifeeroz @MinhazMM @vicpon Do you guys have 1-2h a week to work on this?

**Comment by jpudysz** [comment]
I think the most crucial part is to support React Native 0.62

**Comment by ranjanpoudel1234** [comment]
@RoyceLeonD I am up to help out when i can as well. As @jpudysz  mentioned, supporting new react native versions and also making sure the UIWebView fixes make it to new viro package are the crucial fixes needed asap.

**Comment by jpudysz** [comment]
Additionally removing GVR is not a solution, so we need to find a way to get rid of old UIWebView and support VR.

**Comment by RoyceLeonD** [comment]
Hey Guys, I can give you some updates about the future of Viro. Firstly, I have decided to contact the Viro team and help do some summer cleaning on the repository. But I can only dedicate a couple of hours a week @jpudysz @ranjanpoudel1234 We can work together to come up with a plan and bring the project back to life. 

For now, I can clean up the issues page. And come up with some statistics, and then we can return to create a plan of action. Hopefully, we can turn this ship around in the next couple of weeks. If anyone is interested in helping please like this post. So that we can create an open-source working group.

Let's build the features we want to see from Viro.

-Royce

**Comment by Turtleted21** [comment]
It's the only solution for AR/VR free open source for react native. This API can't die.
I am not a programmer, I'm graphist, perhaps I can help to test 3D model.
Actually we can't use release 2.17 because of this bug : https://github.com/viromedia/viro/issues/763

**Comment by padidas** [comment]
> Let's build the features we want to see from Viro.
> 
> -Royce

Hey @RoyceLeonD @jpudysz @ranjanpoudel1234 @Turtleted21 is there any progress or news to share with us? :)

**Comment by ranjanpoudel1234** [comment]
I am using this library mostly for fbx/vrx rendering using ViroScene and Viro3dObject, in other words for AR. I started looking into the code structure and how its setup. What I am trying to understand is, when we make changes to native modules in ViroCore, do we have to rebuild the renderer every time and import it on the Viro project to be able to debug the changes ? Or have you guys figured out any other easier ways. @RoyceLeonD @jpudysz @dthian ?

**Comment by RoyceLeonD** [comment]
@ranjanpoudel1234 @padidas @jpudysz @Turtleted21 Could you guys dm me on the viro slack: https://viromedia.com/ (found on the bottom of the page).

I can share more info about the architecture of viro, and then we can work together to come up with a plan of action, and work to distribute the workload. I have a basic map, and a pretty good architecture understanding of the whole stack including the automated testing.

I can make a slack channel for us to discuss because more than likely we are also going to have to revitalize the community since it is impossible to get like a small group of devs to take on a huge challenge.

But I have been scoping this project for the past month, and I can say without a doubt, that we can come up with a plan and really make amazing updates!!!

Untill then, Direct message me on the Viro Slack. And I will put us all in a group. Slack name: Royce

**Comment by ranjanpoudel1234** [comment]
@RoyceLeonD who do I ask for invitation to that slack channel ? Looks like I will need viromedia domain account.

**Comment by RoyceLeonD** [comment]
> @RoyceLeonD who do I ask for invitation to that slack channel ? Looks like I will need viromedia domain account.

Hey @ranjanpoudel1234 here is the invite link: https://virodevelopers.slack.com/join/shared_invite/enQtMzI3MzgwNDM2NDM5LTdhMjg5OTJkZGEwYmI0Yzg0N2JkMzJhODVmNmY4YmUyOGY4YjMyZmFmMGFhMTMyMzZiYzU0MGUxMGIzZDFiNjY#/

**Comment by ranjanpoudel1234** [comment]
I am in, thanks @RoyceLeonD

**Comment by RoyceLeonD** [comment]
Thanks, everyone for participating in this thread. I am going to close it, and for future people reading it. Come join us in Slack. I also hope to see you @ranjanpoudel1234 @Turtleted21 @jpudysz @padidas @nazmifeeroz @MinhazMM @visionari-labs at the virtual The Round Table next week. To discuss and talk about the next steps for Viro.

Invites are on Slack, dates will be sent out early next week.
