### ISSUE TITLE
Viro is PWA or Native?

### ISSUE THREAD

**Issue by GUILLALAB** [viromedia/viro#876]
Hello,

I'm new to Viro and I would like to know if Viro can be use for PWA app?
I'm creating an application with React native targetting android & IOS devices.
My desire is that the app integrate Viro and also that the app is accessible and usable directly from a web url ( not downloaded from app store or play stores)

Is it possible?

Thanks you by advance
Franck

**Comment by Turtleted21** [comment]
no it's android & IOS only

**Comment by GUILLALAB** [comment]
> no it's android & IOS only

Thanks you very much.
What technology would you suggest me to do AR with web? (Need surface detection and place object)

**Comment by RoyceLeonD** [comment]
@GUILLALAB Are you doing WebXR for both Android and IOS?

**Comment by GUILLALAB** [comment]
> @GUILLALAB Are you doing WebXR for both Android and IOS?

Currently I've a prototype in native android using arcore.
webAR (webxr) could be a solution to my need  for PWA. it seems surface detection works well on android and ios.

**Comment by Turtleted21** [comment]
sketchfab but $

**Comment by RoyceLeonD** [comment]
@GUILLALAB There is an easy way and a hard way. The easy way: Unity. Unity can handle all of this: but the learning curve is steep. It's kind of webxr (web implementation won't work for iPhone), but you could just publish a native app, and try and use their new App Clips/ rig some functionality together using Quick Look on IOS (both App Clips and Quick look are brand new). 

The hard way: Go full WebXR using three.js, AFrame (or maybe even React360). Your PWA will do all the animations/ view morphing client-side, and your backend will do all the sync/ upload/ multiplayer, etc. Here is the Structure for the hard way:
-  Android's WebXR and Apple's Quick look will be your front end. (However, Apple's quick look is only a model viewer -no real interactivity), however, on both you get surface tracking out of the box.
- And then, you can render whatever models you like,e but your PWA needs to recognize Apple devices because they require a unique file format. (On paper, you are opening up a model viewer)
- Now to add functionality: Then you create hidden HTML CSS masks that track taps, and swipes. Since your PWA on paper will not be allowed to listen to Apple/ Android interactions inside the model viewer. You are going to have to create a janky workaround using HTML/CSS and empty 3D objects. (Honestly, it's like running a man in the middle attack for user action presses)
- Now that you have input (the mask), and output (the viewer), you need to write a bridge (the in-between work). So that when you interact with your mask ("hidden" controls), it updates the model's properties ( orientation, size,e etc.). 
- On the model viewer's side, it thinks it is an animation.
- On the developer, you have create a hidden joystick
- On the user side, it is a cross-platform PWA that has the same functionality in IOS and android. 

Anyways, there are other ways to do this also, using tensorflow.js, but it depends on your application. And as @Turtleted21 mentioned Sketchfab is an option if you want to create a model viewer.

If you are interested in continuing this convo, I recommend joining the Viro Slack: https://viromedia.com/

Feel free to start a thread, or reach out to me personally on the slack. I am closing this thread since it seams resolved.
