### ISSUE TITLE
Offline Application ?

### ISSUE THREAD

**Issue by Zirconiumirish** [viromedia/viro#9]
Hi I have try to install the app from Xcode.
Everything went smooth but I have a question do we always need an internet connection to use the app once installed on iOS devices for exemple ?

Thanks for the answer.

**Comment by manbod** [comment]
You need an internet connection if you are running the debug version of the app on your device. This is because the app needs to connect to the package server (hosted on your development machine) to fetch the JS and assets files. You would not need an internet connection while testing release builds of your app. In release builds, the assets you include are bundled locally within the app.

**Comment by manbod** [comment]
reopening to see if OP had additional comments.
